LEVEL7_MIN_MAINTENANCE_EPISODES = 10
LEVEL7_MIN_RECOVERY_EPISODES = 10
LEVEL7_MIN_NO_CHAT_RESUMES = 3
LEVEL7_MIN_OWNER_VALUE_PAIRS = 30
LEVEL7_MAX_AVOIDABLE_OWNER_INTERRUPTION_RATE = 0.05
LEVEL7_MIN_MAINTENANCE_SELF_RESOLUTION_RATE = 0.95
LEVEL7_MIN_RECOVERY_SELF_RESOLUTION_RATE = 0.95
