INVARIANTS = (
    "INTELLIGENCE_DOES_NOT_INHERIT_AUTHORITY",
    "SOL_REMAINS_SINGLE_CONSTITUTIONAL_KERNEL",
    "NO_DUPLICATE_SCHEDULER",
    "NO_DUPLICATE_MEMORY_ROOT",
    "NO_DUPLICATE_PROVIDER_EXECUTOR",
    "SELF_RESOLVABLE_MAINTENANCE_DOES_NOT_INTERRUPT_OWNER",
    "BLOCKED_LANE_DOES_NOT_FREEZE_INDEPENDENT_LANES",
    "CHAT_IS_NOT_REQUIRED_PERSISTENT_CARRIER",
    "SYNTHETIC_IS_NOT_OPERATIONAL_EVIDENCE",
    "PROVIDER_CLAIM_REQUIRES_PROVIDER_NATIVE_READBACK",
    "LEVEL7_REQUIRES_EMPIRICAL_OPERATION",
    "CONSTITUTION_CANNOT_SELF_EXPAND_OWNER_AUTHORITY",
)


def level7_plus_invariants() -> tuple[str, ...]:
    return INVARIANTS
