from __future__ import annotations
import pytest

TEST_SOURCES = {}

TEST_SOURCES['test_adaptive_wake_cadence'] = "from federation.autopilot_suites_v1.adaptive_wake_cadence import *\ndef test_deadline_tightens(): assert AdaptiveWakeCadence().decide(CadenceInputs('M',deadline_seconds=1800)).next_interval_s<1000\ndef test_stable_backs_off(): assert AdaptiveWakeCadence().decide(CadenceInputs('M',stable_cycles=9)).next_interval_s>3600\ndef test_activity_tightens(): assert AdaptiveWakeCadence().decide(CadenceInputs('M',change_probability=.9)).next_interval_s<3600\ndef test_cost_backs_off(): assert AdaptiveWakeCadence().decide(CadenceInputs('M',cost_pressure=.9)).next_interval_s>3600\ndef test_bounds():\n d=AdaptiveWakeCadence(60,1000).decide(CadenceInputs('M',current_interval_s=99999,stable_cycles=20)); assert 60<=d.next_interval_s<=1000\ndef test_deterministic_jitter(): assert AdaptiveWakeCadence().decide(CadenceInputs('M'))==AdaptiveWakeCadence().decide(CadenceInputs('M'))\ndef test_invalid_ratio():\n try:AdaptiveWakeCadence().decide(CadenceInputs('M',urgency=2)); assert False\n except ValueError:pass\ndef test_mode(): assert AdaptiveWakeCadence().decide(CadenceInputs('M',deadline_seconds=100)).mode in {'FAST','ACTIVE'}\n"

TEST_SOURCES['test_autonomous_deadline_engine'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.autonomous_deadline_engine import *\ndef test_plan_count():\n n=datetime.now(timezone.utc); assert len(AutonomousDeadlineEngine().plan(n+timedelta(days=20),n))==6\ndef test_due_now():\n n=datetime.now(timezone.utc); d=n+timedelta(days=7); assert any(t.state=='DUE_NOW' for t in AutonomousDeadlineEngine().plan(d,n))\ndef test_timezone_required():\n try:AutonomousDeadlineEngine().plan(datetime.now(),datetime.now()); assert False\n except ValueError:pass\ndef test_cadence_day():\n n=datetime.now(timezone.utc); assert AutonomousDeadlineEngine().cadence_ceiling_seconds(n+timedelta(hours=12),n)==900\ndef test_cadence_hour():\n n=datetime.now(timezone.utc); assert AutonomousDeadlineEngine().cadence_ceiling_seconds(n+timedelta(minutes=30),n)==300\ndef test_next_due():\n n=datetime.now(timezone.utc); assert AutonomousDeadlineEngine().next_due(n+timedelta(days=30),n) is not None\ndef test_custom_phase():\n e=AutonomousDeadlineEngine((DeadlinePhase('X',2,'DO_X'),)); n=datetime.now(timezone.utc); assert e.plan(n+timedelta(days=3),n)[0].action=='DO_X'\ndef test_deadline_execution_phase(): assert DEFAULT_PHASES[-1].phase_id=='T0'\n"

TEST_SOURCES['test_autopilot_value_governor'] = "from federation.autopilot_suites_v1.autopilot_value_governor import *\ndef obs(**kw):\n d=dict(automation_id='A',mission_id='M',material_progress=True,calls=2,latency_s=10,owner_minutes_saved=10,false_alerts=0,duplicate_work=0,cost_units=.1,outcome_value=5); d.update(kw); return RunObservation(**d)\ndef test_hold_for_data(): assert AutopilotValueGovernor().evaluate('A').recommendation=='HOLD_FOR_DATA'\ndef test_promote():\n g=AutopilotValueGovernor(); [g.record(obs()) for _ in range(3)]; assert g.evaluate('A').recommendation=='PROMOTE'\ndef test_suspend():\n g=AutopilotValueGovernor(); [g.record(obs(material_progress=False,outcome_value=0,owner_minutes_saved=0,calls=20,cost_units=3)) for _ in range(4)]; assert g.evaluate('A').recommendation=='SUSPEND'\ndef test_backoff_false_alerts():\n g=AutopilotValueGovernor(); [g.record(obs(false_alerts=1,outcome_value=1)) for _ in range(3)]; assert g.evaluate('A').recommendation=='BACKOFF'\ndef test_overlap(): assert AutopilotValueGovernor.overlap_score({'a','b'},{'b','a'})==1\ndef test_merge_candidate(): assert AutopilotValueGovernor().merge_candidate('a','b',{'x','y'},{'x','y'})\ndef test_persistence(tmp_path):\n p=tmp_path/'v.json'; g=AutopilotValueGovernor(p); g.record(obs()); assert len(AutopilotValueGovernor(p).rows)==1\ndef test_invalid_observation():\n try:AutopilotValueGovernor().record(obs(calls=-1)); assert False\n except ValueError:pass\n"

TEST_SOURCES['test_durable_park_resume'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.durable_park_resume import *\ndef test_park_resume(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); s.park('M','CP',WaitPredicate('CI','run','done')); assert s.resume_for_event({'kind':'CI','key':'run','value':'done','event_id':'E'})==('M',)\ndef test_wrong_event(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); s.park('M','CP',WaitPredicate('CI','run','done')); assert not s.resume_for_event({'kind':'EMAIL','key':'run','value':'done'})\ndef test_idempotent_park(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); a=s.park('M','CP',WaitPredicate('CI','run')); b=s.park('M','CP',WaitPredicate('CI','run')); assert a==b\ndef test_cancel(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); s.park('M','CP',WaitPredicate('CI','run')); assert s.cancel('M') and s.get('M')['status']=='CANCELLED'\ndef test_expiry(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); now=datetime.now(timezone.utc); s.park('M','CP',WaitPredicate('CI','run',expires_at=(now-timedelta(seconds=1)).isoformat())); assert s.sweep_expired(now)==('M',)\ndef test_not_before(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); now=datetime.now(timezone.utc); s.park('M','CP',WaitPredicate('CI','run',not_before=(now+timedelta(hours=1)).isoformat())); assert not s.resume_for_event({'kind':'CI','key':'run'},now)\ndef test_persistence(tmp_path):\n p=tmp_path/'p.json'; DurableParkResume(p).park('M','CP',WaitPredicate('CI','run')); assert DurableParkResume(p).get('M')['checkpoint_ref']=='CP'\ndef test_active(tmp_path):\n s=DurableParkResume(tmp_path/'p.json'); s.park('M','CP',WaitPredicate('CI','run')); assert len(s.active())==1\n"

TEST_SOURCES['test_event_wake_mesh'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.event_wake_mesh import *\ndef e(**kw):\n d=dict(event_id='E1',source='github',event_type='CI_DONE',subject='pr:1',occurred_at='2026-09-05T00:00:00+00:00'); d.update(kw); return EventEnvelope(**d)\ndef test_match():\n m=EventWakeMesh(); m.register(Subscription('S','M',sources=('github',),event_types=('CI_DONE',))); assert m.ingest(e()).matched_missions==('M',)\ndef test_dedupe():\n m=EventWakeMesh(); m.register(Subscription('S','M')); m.ingest(e()); assert m.ingest(e()).duplicate_suppressed\ndef test_materiality():\n m=EventWakeMesh(); m.register(Subscription('S','M',min_materiality=.8)); assert not m.ingest(e(materiality=.2)).matched_missions\ndef test_labels():\n m=EventWakeMesh(); m.register(Subscription('S','M',required_labels=('legal',))); assert m.ingest(e(labels=('legal',))).matched_missions\ndef test_subject_filter():\n m=EventWakeMesh(); m.register(Subscription('S','M',subjects=('x',))); assert not m.ingest(e()).matched_missions\ndef test_debounce():\n m=EventWakeMesh(); m.register(Subscription('S','M',debounce_seconds=60)); now=datetime.now(timezone.utc); m.ingest(e(event_id='1'),now); r=m.ingest(e(event_id='2'),now+timedelta(seconds=10)); assert r.debounce_suppressed==('S',)\ndef test_invalidation_keys(): assert 'subject:pr:1' in EventWakeMesh().ingest(e()).invalidation_keys\ndef test_collision():\n m=EventWakeMesh(); m.register(Subscription('S','M'))\n try:m.register(Subscription('S','X')); assert False\n except ValueError:pass\n"

TEST_SOURCES['test_external_wait_state_machine'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.external_wait_state_machine import *\ndef test_wait_resume():\n s=ExternalWaitStateMachine(); s.wait('M',WaitCondition('WAITING_FOR_CI','run','done')); assert s.on_event({'wait_state':'WAITING_FOR_CI','key':'run','value':'done','event_id':'E'})==('M',)\ndef test_wrong_value():\n s=ExternalWaitStateMachine(); s.wait('M',WaitCondition('WAITING_FOR_CI','run','done')); assert not s.on_event({'wait_state':'WAITING_FOR_CI','key':'run','value':'bad'})\ndef test_invalid_state():\n try:ExternalWaitStateMachine().wait('M',WaitCondition('WAITING_FOR_MAGIC','x')); assert False\n except ValueError:pass\ndef test_complete_terminal():\n s=ExternalWaitStateMachine(); s.complete('M')\n try:s.wait('M',WaitCondition('WAITING_FOR_CI','x')); assert False\n except ValueError:pass\ndef test_cancel(): s=ExternalWaitStateMachine(); s.cancel('M'); assert s.missions['M'].state=='CANCELLED'\ndef test_timeout():\n now=datetime.now(timezone.utc); s=ExternalWaitStateMachine(); s.wait('M',WaitCondition('WAITING_FOR_CI','x',expires_at=(now-timedelta(seconds=1)).isoformat())); assert s.timeout(now)==('M',)\ndef test_not_before():\n now=datetime.now(timezone.utc); s=ExternalWaitStateMachine(); s.wait('M',WaitCondition('WAITING_FOR_CI','x',not_before=(now+timedelta(hours=1)).isoformat())); assert not s.on_event({'wait_state':'WAITING_FOR_CI','key':'x'},now)\ndef test_resume_count():\n s=ExternalWaitStateMachine(); s.wait('M',WaitCondition('WAITING_FOR_CI','x')); s.on_event({'wait_state':'WAITING_FOR_CI','key':'x'}); assert s.missions['M'].resume_count==1\n"

TEST_SOURCES['test_fabric'] = "from federation.autopilot_suites_v1.event_wake_mesh import EventEnvelope,Subscription\nfrom federation.autopilot_suites_v1.durable_park_resume import WaitPredicate\nfrom federation.autopilot_suites_v1.fabric import *\ndef test_suite_count(tmp_path): assert AutopilotSuitesFabric(tmp_path).suite_count==11\ndef test_event_wakes(tmp_path):\n f=AutopilotSuitesFabric(tmp_path); f.event_mesh.register(Subscription('S','M',event_types=('CI_DONE',),subjects=('run',))); e=EventEnvelope('E','github','CI_DONE','run','2026-09-05T00:00:00+00:00'); assert f.handle_event(e).woken_missions==('M',)\ndef test_event_resumes_park(tmp_path):\n f=AutopilotSuitesFabric(tmp_path); f.park.park('M','CP',WaitPredicate('CI_DONE','run')); e=EventEnvelope('E','github','CI_DONE','run','2026-09-05T00:00:00+00:00'); assert 'M' in f.handle_event(e).resumed_missions\ndef test_no_authority(tmp_path):\n f=AutopilotSuitesFabric(tmp_path); e=EventEnvelope('E','x','Y','z','2026-09-05T00:00:00+00:00'); r=f.handle_event(e); assert r.authority_delta=='NONE' and not r.external_effect\ndef test_registry_size(): assert len(SUITE_IDS)==11\n"

TEST_SOURCES['test_mission_air_traffic_control'] = "from federation.autopilot_suites_v1.mission_air_traffic_control import *\ndef m(i,**kw):\n d=dict(mission_id=i,urgency=.5,deadline_pressure=.5,expected_value=.5,dependency_unlock=.5,information_gain=.5,completion_proximity=.5,owner_burden_reduction=.5,risk=.1,cost=.1,conflict_domain=i); d.update(kw); return MissionCandidate(**d)\ndef test_select_limit(): assert len(MissionAirTrafficControl(2).select([m('1'),m('2'),m('3')]).selected)==2\ndef test_blocked_held(): assert ('1','BLOCKED') in MissionAirTrafficControl().select([m('1',blocked=True)]).held\ndef test_waiting_held(): assert ('1','WAITING') in MissionAirTrafficControl().select([m('1',waiting=True)]).held\ndef test_domain_serialization():\n r=MissionAirTrafficControl(4,1).select([m('1',conflict_domain='x'),m('2',conflict_domain='x')]); assert len(r.selected)==1\ndef test_high_value_wins():\n r=MissionAirTrafficControl(1).select([m('a',expected_value=.1),m('b',expected_value=1)]); assert r.selected==('b',)\ndef test_age_starvation(): assert MissionAirTrafficControl.score(m('a',age_minutes=10000))>MissionAirTrafficControl.score(m('a',age_minutes=0))\ndef test_invalid_ratio():\n try:MissionAirTrafficControl.score(m('a',risk=2)); assert False\n except ValueError:pass\ndef test_scores_present(): assert len(MissionAirTrafficControl().select([m('1')]).scores)==1\n"

TEST_SOURCES['test_opportunity_autopilot'] = "from federation.autopilot_suites_v1.opportunity_autopilot import *\ndef sig(**kw):\n d=dict(signal_id='S',kind='REPEATED_MANUAL_PATTERN',frequency=4,shared_missions=2,owner_minutes=30,estimated_value=5,confidence=.8,reversibility=.9,information_gain=.7,implementation_effort=2,evidence_refs=('E',)); d.update(kw); return OpportunitySignal(**d)\ndef test_discover(): assert OpportunityAutopilot().discover([sig()])[0].state=='EXPERIMENT_READY'\ndef test_low_frequency_filtered(): assert not OpportunityAutopilot().discover([sig(frequency=1,shared_missions=1)])\ndef test_new_capability_allowed(): assert OpportunityAutopilot().discover([sig(kind='NEW_CAPABILITY',frequency=0,shared_missions=0)])\ndef test_ranking():\n r=OpportunityAutopilot().discover([sig(signal_id='a',estimated_value=1),sig(signal_id='b',estimated_value=10)]); assert r[0].source_signal=='b'\ndef test_low_confidence_evidence_first(): assert OpportunityAutopilot().discover([sig(confidence=.2)])[0].state=='EVIDENCE_FIRST'\ndef test_effort_positive():\n try:OpportunityAutopilot().discover([sig(implementation_effort=0)]); assert False\n except ValueError:pass\ndef test_unknown_kind_ignored(): assert not OpportunityAutopilot().discover([sig(kind='X')])\ndef test_experiment_has_readback(): assert 'READBACK' in OpportunityAutopilot().discover([sig()])[0].experiment\n"

TEST_SOURCES['test_persistent_mission_sandbox'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.persistent_mission_sandbox import *\ndef test_put_read(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M'); s.put_text('a.txt','hi'); assert s.read_text('a.txt')=='hi'\ndef test_hash(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M'); h=s.put_text('a','x'); assert h==s.file_hash('a')\ndef test_checkpoint_restore(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M'); s.put_text('a','one'); s.checkpoint('c'); s.put_text('a','two'); s.restore('c'); assert s.read_text('a')=='one'\ndef test_path_traversal(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M')\n try:s.put_text('../x','bad'); assert False\n except ValueError:pass\ndef test_quota(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M',max_bytes=2)\n try:s.put_text('a','123'); assert False\n except ValueError:pass\ndef test_list(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M'); s.put_text('b/a','x'); assert s.list_files()==('b/a',)\ndef test_expiry(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M',ttl_seconds=1); future=datetime.now(timezone.utc)+timedelta(seconds=2); assert s.expired(future)\ndef test_cleanup(tmp_path):\n s=PersistentMissionSandbox(tmp_path,'M',ttl_seconds=1); future=datetime.now(timezone.utc)+timedelta(seconds=2); assert s.cleanup_if_expired(future)\n"

TEST_SOURCES['test_scoped_auto_approval_memory'] = "from datetime import datetime,timezone,timedelta\nfrom federation.autopilot_suites_v1.scoped_auto_approval_memory import *\ndef grant(**kw):\n d=dict(grant_id='G',mission_id='M',effect_classes=('REVERSIBLE_INTERNAL',),target_patterns=('drafts/*',),authorization_ref='AUTH',max_uses=2); d.update(kw); return ApprovalGrant(**d)\ndef req(**kw):\n d=dict(mission_id='M',effect_class='REVERSIBLE_INTERNAL',target='drafts/a',reversible=True,readback_available=True); d.update(kw); return ApprovalRequest(**d)\ndef test_authorize(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant()); assert s.authorize(req()).allowed\ndef test_wrong_target(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant()); assert not s.authorize(req(target='prod/a')).allowed\ndef test_usage_limit(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant(max_uses=1)); assert s.authorize(req()).allowed; assert not s.authorize(req()).allowed\ndef test_revoke(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant()); s.revoke('G'); assert not s.authorize(req()).allowed\ndef test_expired(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant(expires_at=(datetime.now(timezone.utc)-timedelta(seconds=1)).isoformat())); assert not s.authorize(req()).allowed\ndef test_requires_reversible(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant()); assert not s.authorize(req(reversible=False)).allowed\ndef test_requires_readback(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant()); assert not s.authorize(req(readback_available=False)).allowed\ndef test_collision(tmp_path):\n s=ScopedApprovalMemory(tmp_path/'a.json'); s.add(grant())\n try:s.add(grant(mission_id='X')); assert False\n except ValueError:pass\n"

TEST_SOURCES['test_trigger_recovery_reflexes'] = "from federation.autopilot_suites_v1.trigger_recovery_reflexes import *\ndef sig(**kw):\n d=dict(signal_id='S',trigger_type='CI_FAIL',fingerprint='DEPENDENCY:PY',route_id='R'); d.update(kw); return FailureSignal(**d)\ndef test_default_reflex(): assert TriggerRecoveryReflexes.defaults().decide(sig()).reflex_id=='REFLEX-CI-DEPENDENCY'\ndef test_no_match(): assert TriggerRecoveryReflexes.defaults().decide(sig(trigger_type='X')).state=='NO_REFLEX'\ndef test_effect_hold(): assert TriggerRecoveryReflexes.defaults().decide(sig(effect_class='HIGH_CONSEQUENCE')).state=='HELD_EFFECT_CLASS'\ndef test_changed_route_required_after_repeat():\n e=TriggerRecoveryReflexes.defaults(); e.decide(sig(signal_id='1')); assert e.decide(sig(signal_id='2')).require_changed_route\ndef test_circuit_opens():\n e=TriggerRecoveryReflexes.defaults(); r=None\n for i in range(3):r=e.decide(sig(signal_id=str(i)))\n assert r.circuit_open\ndef test_repeat_reflex_immediate_open(): assert TriggerRecoveryReflexes.defaults().decide(sig(trigger_type='REPEATED_FAILURE',fingerprint='X')).circuit_open\ndef test_register_collision():\n e=TriggerRecoveryReflexes(); d=ReflexDefinition('R','X','*',('A',)); e.register(d)\n try:e.register(ReflexDefinition('R','Y','*',('B',))); assert False\n except ValueError:pass\ndef test_actions_nonempty(): assert TriggerRecoveryReflexes.defaults().decide(sig()).actions\n"

CASES = []
for module_name, source in TEST_SOURCES.items():
    namespace = {"__name__": f"_autopilot_court_{module_name}"}
    exec(compile(source, f"<{module_name}>", "exec"), namespace)
    for name, fn in sorted(namespace.items()):
        if name.startswith("test_") and callable(fn):
            CASES.append(pytest.param(fn, id=f"{module_name}::{name}"))

assert len(CASES) == 93, f"expected 93 local-qualified cases, found {len(CASES)}"

@pytest.mark.parametrize("case", CASES)
def test_federation_autopilot_suites_v1(case):
    import inspect
    import tempfile
    from pathlib import Path
    params = inspect.signature(case).parameters
    if "tmp_path" in params:
        with tempfile.TemporaryDirectory(prefix="autopilot-suite-court-") as d:
            case(Path(d))
    else:
        case()
