#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/transaction.h"
#include <filesystem>
#include <cstdio>
#include <string>

using namespace fuse;

static Digest256 d(const char* text){Digest256 out{};sha256({(const u8*)text,(u64)std::char_traits<char>::length(text)},&out);return out;}
static std::wstring root_for(const wchar_t* id){auto root=std::filesystem::temp_directory_path()/L"FUSE-GenesisAdmission"/id;std::error_code ec;std::filesystem::remove_all(root,ec);std::filesystem::create_directories(root,ec);return root.wstring();}
static Status append_task_marker(Runtime*r,const Id128&mission,u64 version,const Digest256&task,EventType type){FcbWriter w{};auto st=fcb_begin(&w,(u16)(0x4000+(u32)type),0);if(st!=Status::Ok)return st;if((st=fcb_put_bytes(&w,1,FcbType::DIGEST256,{task.bytes.data(),32}))!=Status::Ok)return st;Buffer payload;if((st=fcb_finish(&w,&payload,nullptr))!=Status::Ok)return st;return append_event(r,mission,version,type,{payload.data(),(u64)payload.size()});}
static Status prime_task(Runtime*r,const Id128&mission,const Digest256&task,const char*nonce_seed,const char*idem_seed){auto st=append_task_marker(r,mission,1,task,EventType::MISSION_CREATED);if(st!=Status::Ok)return st;if((st=append_task_marker(r,mission,1,task,EventType::TASK_RECEIVED))!=Status::Ok)return st;if((st=append_task_marker(r,mission,1,task,EventType::TASK_VALIDATED))!=Status::Ok)return st;auto nonce=d(nonce_seed);if((st=nonce_claim(r,mission,1,task,nonce))!=Status::Ok)return st;auto idem=d(idem_seed);if((st=idempotency_claim(r,mission,1,task,idem))!=Status::Ok)return st;return append_task_marker(r,mission,1,task,EventType::ACTION_PREPARED);}
static bool report(const char*id,bool ok){std::printf("%s %s\n",ok?"PASS":"FAIL",id);return ok;}

static bool adv001(){Runtime r{};auto root=root_for(L"ADV-001");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-001-M");auto t=d("ADV-001-T");auto a=d("ADV-001-N-A"),b=d("ADV-001-N-B");bool ok=nonce_claim(&r,m,1,t,a)==Status::Ok&&nonce_claim(&r,m,1,t,b)==Status::Ok;runtime_close(&r);if(runtime_open(root,&r)!=Status::Ok)return false;ok=ok&&nonce_claim(&r,m,1,t,a)==Status::NonceReplay;runtime_close(&r);return ok;}
static bool adv002(){Runtime r{};auto root=root_for(L"ADV-002");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-002-M");auto a=d("ADV-002-T-A"),b=d("ADV-002-T-B"),n=d("ADV-002-N");bool ok=nonce_claim(&r,m,1,a,n)==Status::Ok&&nonce_claim(&r,m,1,b,n)==Status::NonceReplay;runtime_close(&r);return ok;}
static bool adv003(){Runtime r{};auto root=root_for(L"ADV-003");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-003-M");PreparedAction a{},b{};a.mission_id=m;a.task_id=id_from_seed("ADV-003-A");a.task_digest=d("ADV-003-T-A");a.effect_id=d("ADV-003-E-A");a.prepared_digest=d("ADV-003-P-A");b.mission_id=m;b.task_id=id_from_seed("ADV-003-B");b.task_digest=d("ADV-003-T-B");b.effect_id=d("ADV-003-E-B");b.prepared_digest=d("ADV-003-P-B");bool ok=prime_task(&r,m,a.task_digest,"ADV-003-N-A","ADV-003-I-A")==Status::Ok&&prime_task(&r,m,b.task_digest,"ADV-003-N-B","ADV-003-I-B")==Status::Ok;ExecutionPermit pa{},pb{};ok=ok&&permit_issue(&r,&a,&pa)==Status::Ok&&permit_issue(&r,&b,&pb)==Status::Ok&&pa.permit_id!=pb.permit_id;ok=ok&&permit_consume(&r,&pa)==Status::Ok;bool ca=false,cb=false;ok=ok&&permit_consumed(&r,pa.permit_id,&ca)==Status::Ok&&permit_consumed(&r,pb.permit_id,&cb)==Status::Ok&&ca&&!cb;ok=ok&&permit_consume(&r,&pb)==Status::Ok;runtime_close(&r);if(runtime_open(root,&r)!=Status::Ok)return false;ca=cb=false;ok=ok&&permit_consumed(&r,pa.permit_id,&ca)==Status::Ok&&permit_consumed(&r,pb.permit_id,&cb)==Status::Ok&&ca&&cb;runtime_close(&r);return ok;}
static bool adv004(){Runtime r{};auto root=root_for(L"ADV-004");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-004-M");auto a=d("ADV-004-T-A"),b=d("ADV-004-T-B");bool ok=append_task_marker(&r,m,1,a,EventType::TASK_PROVEN)==Status::Ok&&append_task_marker(&r,m,1,a,EventType::MISSION_COMPLETE_VERIFIED)==Status::Ok;TaskSecurityProjection pa{},pb{};ok=ok&&project_task(&r,m,1,a,&pa)==Status::Ok&&project_task(&r,m,1,b,&pb)==Status::Ok&&pa.task_proven&&pa.mission_complete&&!pb.task_proven&&!pb.mission_complete;runtime_close(&r);return ok;}
static bool adv005(){Runtime r{};auto root=root_for(L"ADV-005");if(runtime_open(root,&r)!=Status::Ok)return false;auto ma=id_from_seed("ADV-005-M-A"),mb=id_from_seed("ADV-005-M-B");auto t=d("ADV-005-T");bool ok=append_task_marker(&r,ma,1,t,EventType::TASK_PROVEN)==Status::Ok&&append_task_marker(&r,ma,1,t,EventType::MISSION_COMPLETE_VERIFIED)==Status::Ok;TaskSecurityProjection pa{},pb{};ok=ok&&project_task(&r,ma,1,t,&pa)==Status::Ok&&project_task(&r,mb,1,t,&pb)==Status::Ok&&pa.task_proven&&pa.mission_complete&&!pb.task_proven&&!pb.mission_complete;runtime_close(&r);return ok;}
static bool adv006(){Runtime r{};auto root=root_for(L"ADV-006");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-006-M");auto t=d("ADV-006-T"),a=d("ADV-006-I-A"),b=d("ADV-006-I-B");bool ok=idempotency_claim(&r,m,1,t,a)==Status::Ok&&idempotency_claim(&r,m,1,t,b)==Status::Ok;runtime_close(&r);if(runtime_open(root,&r)!=Status::Ok)return false;ok=ok&&idempotency_claim(&r,m,1,t,a)==Status::IdempotencyReplay;runtime_close(&r);return ok;}
static bool adv007(){Runtime r{};auto root=root_for(L"ADV-007");if(runtime_open(root,&r)!=Status::Ok)return false;auto m=id_from_seed("ADV-007-M");PreparedAction a{};a.mission_id=m;a.task_id=id_from_seed("ADV-007-TID");a.task_digest=d("ADV-007-T");a.effect_id=d("ADV-007-E");a.prepared_digest=d("ADV-007-P");ExecutionPermit p{};bool ok=permit_issue(&r,&a,&p)==Status::InvalidArgument;runtime_close(&r);return ok;}

int wmain(){u32 pass=0;pass+=report("ADV-001",adv001());pass+=report("ADV-002",adv002());pass+=report("ADV-003",adv003());pass+=report("ADV-004",adv004());pass+=report("ADV-005",adv005());pass+=report("ADV-006",adv006());pass+=report("ADV-007",adv007());std::printf("GENESIS_ADMISSION_COURT discovered=7 executed=7 passed=%u failed=%u\n",pass,7-pass);return pass==7?0:117;}
