[CmdletBinding()]
param([string]$SourceRoot=$PSScriptRoot,[string]$OutputRoot=(Join-Path $PSScriptRoot 'out'))
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if($env:OS -ne 'Windows_NT'){throw 'WINDOWS_REQUIRED'}
$SourceRoot=(Resolve-Path -LiteralPath $SourceRoot).Path
New-Item -ItemType Directory -Force -Path $OutputRoot|Out-Null;$OutputRoot=(Resolve-Path -LiteralPath $OutputRoot).Path
function H([string]$p){(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()}
$vswhere="${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe";if(-not(Test-Path $vswhere)){throw 'VSWHERE_MISSING'}
$vs=& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath;if(-not $vs){throw 'MSVC_MISSING'}
$msvcRoot=Get-ChildItem (Join-Path $vs 'VC\Tools\MSVC') -Directory|Sort-Object Name -Descending|Select-Object -First 1
$cl=Join-Path $msvcRoot.FullName 'bin\Hostx64\x64\cl.exe';$link=Join-Path $msvcRoot.FullName 'bin\Hostx64\x64\link.exe';$vcInc=Join-Path $msvcRoot.FullName 'include';$vcLib=Join-Path $msvcRoot.FullName 'lib\x64'
$sdkRoot="${env:ProgramFiles(x86)}\Windows Kits\10";$sdk=Get-ChildItem (Join-Path $sdkRoot 'Lib') -Directory|Sort-Object Name -Descending|Select-Object -First 1;if(-not $sdk){throw 'WINDOWS_SDK_MISSING'}
$v=$sdk.Name;$umInc=Join-Path $sdkRoot "Include\$v\um";$sharedInc=Join-Path $sdkRoot "Include\$v\shared";$ucrtInc=Join-Path $sdkRoot "Include\$v\ucrt";$umLib=Join-Path $sdkRoot "Lib\$v\um\x64";$ucrtLib=Join-Path $sdkRoot "Lib\$v\ucrt\x64"
$files=@('include\fuse\base.h','include\fuse\status.h','include\fuse\crypto.h','include\fuse\format.h','include\fuse\store.h','include\fuse\identity.h','include\fuse\capability.h','include\fuse\transaction.h','include\fuse\court.h','src\fuse_entry.cpp','src\base.cpp','src\win_crypto.cpp','src\win_file.cpp','src\win_path.cpp','src\win_process.cpp','src\fcb1.cpp','src\fsj1.cpp','src\journal.cpp','src\recovery.cpp','src\object_store.cpp','src\identity.cpp','src\transaction.cpp','src\capability_registry.cpp','src\capability_system_status.cpp','src\capability_sha256.cpp','src\capability_file_hash.cpp','src\capability_file_write.cpp','court\court_core.cpp','court\court_io.cpp')
if($files.Count -ne 29){throw "SOURCE_DENOMINATOR_CHANGED:$($files.Count)"}
$material=@();foreach($r in $files){$p=Join-Path $SourceRoot $r;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "SOURCE_MISSING:$r"};$i=Get-Item $p;$material+="$($r.Replace('\','/'))`t$($i.Length)`t$(H $p)"}
$treePath=Join-Path $OutputRoot 'source-tree.material';[IO.File]::WriteAllText($treePath,($material -join "`n")+"`n",[Text.UTF8Encoding]::new($false));$treeHash=H $treePath
$cpp=$files|Where-Object{$_ -like '*.cpp'};if($cpp.Count -ne 20){throw "COMPILATION_UNIT_DENOMINATOR_CHANGED:$($cpp.Count)"}
$common=@('/nologo','/c','/O2','/W4','/WX','/EHsc','/GR-','/GS','/guard:cf','/std:c++20','/permissive-','/MT',"/I$(Join-Path $SourceRoot 'include')","/I$vcInc","/I$umInc","/I$sharedInc","/I$ucrtInc")
$linkFlags=@('/NOLOGO','/SUBSYSTEM:CONSOLE','/MACHINE:X64','/DYNAMICBASE','/HIGHENTROPYVA','/NXCOMPAT','/GUARD:CF','/OPT:REF','/OPT:ICF','/Brepro',"/LIBPATH:$vcLib","/LIBPATH:$umLib","/LIBPATH:$ucrtLib")
function BuildOne([string]$name,[string]$padding){$root=Join-Path $OutputRoot ($name+$padding);Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue;$obj=Join-Path $root 'obj';$bin=Join-Path $root 'bin';New-Item -ItemType Directory -Force -Path $obj,$bin|Out-Null;$objects=@();foreach($r in $cpp){$src=Join-Path $SourceRoot $r;$o=Join-Path $obj (($r -replace '[\\/:]','_')+'.obj');& $cl @common "/Fo$o" $src;if($LASTEXITCODE -ne 0){throw "COMPILE_FAILED:$r"};$objects+=$o};$exe=Join-Path $bin 'fuse-genesis.exe';& $link @linkFlags "/OUT:$exe" @objects kernel32.lib bcrypt.lib ncrypt.lib advapi32.lib;if($LASTEXITCODE -ne 0){throw 'LINK_FAILED'};& $exe --self-court;if($LASTEXITCODE -ne 0){throw "SELF_COURT_FAILED:$name"};$canary=Join-Path $root 'mvs-canary';& $exe --mvs-canary $canary;if($LASTEXITCODE -ne 0){throw "MVS_CANARY_FAILED:$name"};& $exe --mvs-canary $canary;if($LASTEXITCODE -ne 0){throw "MVS_DUPLICATE_COURT_FAILED:$name"};[ordered]@{exe=$exe;sha256=H $exe;bytes=(Get-Item $exe).Length}}
$a=BuildOne 'A' '';$b=BuildOne 'B' '-different-path-length-xxxxxxxxxxxxxxxx';if($a.sha256 -ne $b.sha256 -or $a.bytes -ne $b.bytes){throw "R2_REPRODUCIBILITY_FAILED:A=$($a.sha256):B=$($b.sha256)"}
$receipt=[ordered]@{schema='FUSE-GENESIS-MVS-BUILD-RECEIPT-V1';state='GENESIS_MVS_PROVEN_HOSTED_WINDOWS_CANDIDATE';source_file_count=29;compilation_unit_count=20;source_tree_sha256=$treeHash;self_court_registry_sha256='70fb55e6ecc5f1ae7c181a60473637a6c59f5e7430f41471afe16d06d1bb2686';self_court='48_OF_48_REQUIRED';build_a_sha256=$a.sha256;build_b_sha256=$b.sha256;byte_identical=$true;network_required=$false;provider_runtime=$false;dotnet_runtime=$false;python_runtime=$false;node_runtime=$false;build_profile='G0_STATIC_BOOTSTRAP';embedded_msvc_static_runtime='DECLARED';owner_pc_physical_proof=$false;truth_boundary='Hosted Windows MVS proof only. Owner-PC physical proof remains separate.'}
$receiptPath=Join-Path $OutputRoot 'genesis-build-receipt.json';$receipt|ConvertTo-Json -Depth 8|Set-Content $receiptPath -Encoding utf8NoBOM;Write-Host ($receipt|ConvertTo-Json -Depth 8 -Compress)
