[CmdletBinding()]
param([string]$SourceRoot=$PSScriptRoot,[string]$OutputRoot=(Join-Path $PSScriptRoot 'out'))
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if($env:OS -ne 'Windows_NT'){throw 'WINDOWS_REQUIRED'}
$SourceRoot=(Resolve-Path -LiteralPath $SourceRoot).Path;New-Item -ItemType Directory -Force -Path $OutputRoot|Out-Null;$OutputRoot=(Resolve-Path -LiteralPath $OutputRoot).Path
function Get-LogosSha256([string]$p){(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()}
$vswhere="${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe";if(-not(Test-Path $vswhere)){throw 'VSWHERE_MISSING'};$vs=& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath;if(-not $vs){throw 'MSVC_MISSING'}
$msvc=Get-ChildItem (Join-Path $vs 'VC\Tools\MSVC') -Directory|Sort-Object Name -Descending|Select-Object -First 1;$cl=Join-Path $msvc.FullName 'bin\Hostx64\x64\cl.exe';$link=Join-Path $msvc.FullName 'bin\Hostx64\x64\link.exe';$vcInc=Join-Path $msvc.FullName 'include';$vcLib=Join-Path $msvc.FullName 'lib\x64'
$sdkRoot="${env:ProgramFiles(x86)}\Windows Kits\10";$sdk=Get-ChildItem (Join-Path $sdkRoot 'Lib') -Directory|Sort-Object Name -Descending|Select-Object -First 1;if(-not $sdk){throw 'WINDOWS_SDK_MISSING'};$v=$sdk.Name;$umInc=Join-Path $sdkRoot "Include\$v\um";$sharedInc=Join-Path $sdkRoot "Include\$v\shared";$ucrtInc=Join-Path $sdkRoot "Include\$v\ucrt";$umLib=Join-Path $sdkRoot "Lib\$v\um\x64";$ucrtLib=Join-Path $sdkRoot "Lib\$v\ucrt\x64"
$files=@('include\logos_base.h','include\logos_format.h','include\logos_store.h','include\logos_graph.h','include\logos_ingest.h','include\logos_court.h','src\main.cpp','src\base.cpp','src\format.cpp','src\object_store.cpp','src\ledger.cpp','src\graph.cpp','src\ingest.cpp','src\contradiction.cpp','src\views.cpp','src\verify.cpp','court\graph_court.cpp','court\compiler_court.cpp');if($files.Count-ne 18){throw "SOURCE_DENOMINATOR_CHANGED:$($files.Count)"};$cpp=$files|Where-Object{$_ -like '*.cpp'};if($cpp.Count-ne 12){throw "COMPILATION_UNIT_DENOMINATOR_CHANGED:$($cpp.Count)"}
$material=@();foreach($r in $files){$p=Join-Path $SourceRoot $r;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "SOURCE_MISSING:$r"};$i=Get-Item $p;$material+="$($r.Replace('\','/'))`t$($i.Length)`t$(Get-LogosSha256 $p)"};$treePath=Join-Path $OutputRoot 'source-tree.material';[IO.File]::WriteAllText($treePath,($material -join "`n")+"`n",[Text.UTF8Encoding]::new($false));$treeHash=Get-LogosSha256 $treePath
$common=@('/nologo','/c','/O2','/W4','/WX','/EHsc','/GR-','/GS','/guard:cf','/std:c++20','/permissive-','/utf-8','/MT','/Brepro',"/I$(Join-Path $SourceRoot 'include')","/I$vcInc","/I$umInc","/I$sharedInc","/I$ucrtInc");$linkFlags=@('/NOLOGO','/SUBSYSTEM:CONSOLE','/MACHINE:X64','/DYNAMICBASE','/HIGHENTROPYVA','/NXCOMPAT','/GUARD:CF','/OPT:REF','/OPT:ICF','/INCREMENTAL:NO','/Brepro',"/LIBPATH:$vcLib","/LIBPATH:$umLib","/LIBPATH:$ucrtLib")
function BuildOne([string]$name,[string]$padding){$root=Join-Path $OutputRoot ($name+$padding);Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue;$obj=Join-Path $root 'obj';$bin=Join-Path $root 'bin';New-Item -ItemType Directory -Force -Path $obj,$bin|Out-Null;$objects=@();foreach($r in $cpp){$src=Join-Path $SourceRoot $r;$o=Join-Path $obj (($r-replace '[\\/:]','_')+'.obj');& $cl @common "/Fo$o" $src|Out-Host;if($LASTEXITCODE-ne 0){throw "COMPILE_FAILED:$r"};$objects+=$o};$exe=Join-Path $bin 'logos.exe';& $link @linkFlags "/OUT:$exe" @objects kernel32.lib|Out-Host;if($LASTEXITCODE-ne 0){throw 'LINK_FAILED'};$court=Join-Path $root 'court';& $exe court $court|Out-Host;if($LASTEXITCODE-ne 0){throw "COURT_FAILED:$name"};[pscustomobject][ordered]@{exe=$exe;sha256=Get-LogosSha256 $exe;bytes=(Get-Item $exe).Length;receipt=(Join-Path $court 'acceptance\receipts\mevs-receipt.json')}}
$a=BuildOne 'A' '';$b=BuildOne 'B' '-different-path-length-xxxxxxxxxxxxxxxx';if($a.sha256-ne $b.sha256-or $a.bytes-ne $b.bytes){throw "R2_REPRODUCIBILITY_FAILED:A=$($a.sha256):B=$($b.sha256)"}
$offlineRoot=Join-Path $OutputRoot 'network-blocked';$ruleBase="FUSE-LOGOS-MEVS-$env:GITHUB_RUN_ID-$env:GITHUB_RUN_ATTEMPT";New-NetFirewallRule -DisplayName "$ruleBase-out" -Direction Outbound -Program $a.exe -Action Block -Profile Any|Out-Null;New-NetFirewallRule -DisplayName "$ruleBase-in" -Direction Inbound -Program $a.exe -Action Block -Profile Any|Out-Null;try{& $a.exe court $offlineRoot|Out-Host;if($LASTEXITCODE-ne 0){throw 'NETWORK_BLOCKED_COURT_FAILED'}}finally{Remove-NetFirewallRule -DisplayName "$ruleBase-out" -ErrorAction SilentlyContinue;Remove-NetFirewallRule -DisplayName "$ruleBase-in" -ErrorAction SilentlyContinue}
$buildReceipt=[ordered]@{schema='FUSE-LOGOS-MEVS-BUILD-RECEIPT-V1';state='LOGOS_MEVS_PROVEN_HOSTED_WINDOWS_CANDIDATE';source_file_count=18;compilation_unit_count=12;graph_court='18_OF_18_REQUIRED';compiler_court='20_OF_20_REQUIRED';source_tree_sha256=$treeHash;build_a_sha256=$a.sha256;build_b_sha256=$b.sha256;byte_identical=$true;network_blocked_court='PASS';mandatory_llm=$false;mandatory_cloud=$false;mandatory_external_database=$false;mandatory_vector_database=$false;owner_pc_physical_proof=$false;truth_boundary='Hosted Windows deterministic LOGOS-MEVS proof only; no production-scale, autonomous-research, historical-truth, Canon-validity or owner-PC claim.'};$buildReceiptPath=Join-Path $OutputRoot 'logos-build-receipt.json';$buildReceipt|ConvertTo-Json -Depth 8|Set-Content $buildReceiptPath -Encoding utf8NoBOM;Write-Host($buildReceipt|ConvertTo-Json -Depth 8 -Compress)
