#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <winioctl.h>
#include "fuse/court.h"
#include <filesystem>
#include <vector>
#include <cstring>

namespace fuse {
Status file_write_durable(const std::wstring&,ByteSpan,bool);Status ensure_directory(const std::wstring&);
static Status make_root(CourtContext*c,const wchar_t*id,FileRoot*out,ObjectStore*store=nullptr){auto root=court_fixture_root(c,id);auto allowed=(std::filesystem::path(root)/L"allowed").wstring();ensure_directory(allowed);auto st=register_root(1,allowed,true,true,out);if(st==Status::Ok&&store){auto o=(std::filesystem::path(root)/L"objects").wstring();st=object_store_open(o,store);}return st;}
#pragma pack(push,1)
struct MountPointReparse{ULONG tag;USHORT dataLength;USHORT reserved;USHORT subOffset;USHORT subLength;USHORT printOffset;USHORT printLength;WCHAR path[1];};
#pragma pack(pop)
static bool create_junction(const std::wstring&junction,const std::wstring&target){std::error_code ec;std::filesystem::create_directories(junction,ec);if(ec)return false;HANDLE h=CreateFileW(junction.c_str(),GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT|FILE_FLAG_BACKUP_SEMANTICS,nullptr);if(h==INVALID_HANDLE_VALUE)return false;std::wstring subst=L"\\??\\"+target,print=target;USHORT sb=(USHORT)(subst.size()*sizeof(wchar_t)),pb=(USHORT)(print.size()*sizeof(wchar_t));size_t pathBytes=sb+sizeof(wchar_t)+pb+sizeof(wchar_t),total=offsetof(MountPointReparse,path)+pathBytes;std::vector<u8> raw(total,0);auto*r=(MountPointReparse*)raw.data();r->tag=IO_REPARSE_TAG_MOUNT_POINT;r->dataLength=(USHORT)(8+pathBytes);r->subOffset=0;r->subLength=sb;r->printOffset=(USHORT)(sb+sizeof(wchar_t));r->printLength=pb;memcpy(r->path,subst.data(),sb);memcpy((u8*)r->path+sb+sizeof(wchar_t),print.data(),pb);DWORD ret=0;BOOL ok=DeviceIoControl(h,FSCTL_SET_REPARSE_POINT,r,(DWORD)total,nullptr,0,&ret,nullptr);CloseHandle(h);return ok==TRUE;}
static CourtResult path_case(const char*id,CourtContext*c){std::wstring wid;for(auto*p=id;*p;p++)wid.push_back((wchar_t)*p);FileRoot r{};auto st=make_root(c,wid.c_str(),&r);if(st!=Status::Ok)return court_fail(id,CourtDomain::PATH,st);if(!strcmp(id,"PTH-001"))return validate_relative_path(L"a\\b.txt")==Status::Ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);if(!strcmp(id,"PTH-002"))return validate_relative_path(L"..\\outside.txt")!=Status::Ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);if(!strcmp(id,"PTH-003")){bool ok=validate_relative_path(L"C:\\x")!=Status::Ok&&validate_relative_path(L"\\\\server\\share\\x")!=Status::Ok&&validate_relative_path(L"\\x")!=Status::Ok;return ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);}if(!strcmp(id,"PTH-004")){auto root=std::filesystem::path(r.configured_path).parent_path();auto evil=(root/L"allowed-Evil").wstring();ensure_directory(evil);file_write_durable((std::filesystem::path(evil)/L"x.txt").wstring(),{(const u8*)"x",1},false);FileHashResult h{};return file_hash_authorized(&r,L"..\\allowed-Evil\\x.txt",&h)!=Status::Ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);}if(!strcmp(id,"PTH-005")){auto outside=(std::filesystem::path(r.configured_path).parent_path()/L"outside").wstring();ensure_directory(outside);file_write_durable((std::filesystem::path(outside)/L"secret.txt").wstring(),{(const u8*)"s",1},false);auto link=(std::filesystem::path(r.configured_path)/L"link").wstring();if(!create_junction(link,outside))return court_fail(id,CourtDomain::PATH,Status::TestFailed);FileHashResult h{};return file_hash_authorized(&r,L"link\\secret.txt",&h)!=Status::Ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);}if(!strcmp(id,"PTH-006"))return validate_relative_path(L"x.txt:ads")!=Status::Ok?court_pass(id,CourtDomain::PATH):court_fail(id,CourtDomain::PATH,Status::TestFailed);return court_fail(id,CourtDomain::PATH,Status::Unsupported);}
CourtResult court_pth_001(CourtContext*c){return path_case("PTH-001",c);}CourtResult court_pth_002(CourtContext*c){return path_case("PTH-002",c);}CourtResult court_pth_003(CourtContext*c){return path_case("PTH-003",c);}CourtResult court_pth_004(CourtContext*c){return path_case("PTH-004",c);}CourtResult court_pth_005(CourtContext*c){return path_case("PTH-005",c);}CourtResult court_pth_006(CourtContext*c){return path_case("PTH-006",c);}
static Status bounded_read(const FileRoot*r,const std::wstring&rel,u64 max,Buffer*out){FileHashResult h{};auto st=file_hash_authorized(r,rel,&h);if(st!=Status::Ok)return st;if(h.size>max)return Status::BufferTooSmall;FileIdentity id{};return file_read_authorized(r,rel,out,&id);}
static CourtResult file_case(const char*id,CourtContext*c){std::wstring wid;for(auto*p=id;*p;p++)wid.push_back((wchar_t)*p);FileRoot r{};ObjectStore s{};auto st=make_root(c,wid.c_str(),&r,&s);if(st!=Status::Ok)return court_fail(id,CourtDomain::FILE_IO,st);auto p=(std::filesystem::path(r.configured_path)/L"data.bin").wstring();file_write_durable(p,{(const u8*)"abcdef",6},false);if(!strcmp(id,"FIL-001")){Buffer b;FileIdentity fi{};st=file_read_authorized(&r,L"data.bin",&b,&fi);ObjectRef o{};if(st==Status::Ok)st=object_put(&s,{b.data(),(u64)b.size()},1,&o);return st==Status::Ok&&object_verify(&s,&o)==Status::Ok?court_pass(id,CourtDomain::FILE_IO):court_fail(id,CourtDomain::FILE_IO,st);}if(!strcmp(id,"FIL-002")){FileHashResult h{};Digest256 exp{};sha256({(const u8*)"abcdef",6},&exp);st=file_hash_authorized(&r,L"data.bin",&h);return st==Status::Ok&&h.digest==exp?court_pass(id,CourtDomain::FILE_IO):court_fail(id,CourtDomain::FILE_IO,st);}if(!strcmp(id,"FIL-003")){Buffer b;st=bounded_read(&r,L"data.bin",3,&b);return st==Status::BufferTooSmall?court_pass(id,CourtDomain::FILE_IO):court_fail(id,CourtDomain::FILE_IO,Status::TestFailed);}if(!strcmp(id,"FIL-004")){HANDLE h=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);HANDLE w=CreateFileW(p.c_str(),GENERIC_WRITE,0,nullptr,OPEN_EXISTING,0,nullptr);bool safe=(h!=INVALID_HANDLE_VALUE&&w==INVALID_HANDLE_VALUE);if(w!=INVALID_HANDLE_VALUE)CloseHandle(w);if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);return safe?court_pass(id,CourtDomain::FILE_IO):court_fail(id,CourtDomain::FILE_IO,Status::TestFailed);}if(!strcmp(id,"FIL-005")){FileHashResult h{};st=file_hash_authorized(&r,L".",&h);return st!=Status::Ok?court_pass(id,CourtDomain::FILE_IO):court_fail(id,CourtDomain::FILE_IO,Status::TestFailed);}return court_fail(id,CourtDomain::FILE_IO,Status::Unsupported);}
CourtResult court_fil_001(CourtContext*c){return file_case("FIL-001",c);}CourtResult court_fil_002(CourtContext*c){return file_case("FIL-002",c);}CourtResult court_fil_003(CourtContext*c){return file_case("FIL-003",c);}CourtResult court_fil_004(CourtContext*c){return file_case("FIL-004",c);}CourtResult court_fil_005(CourtContext*c){return file_case("FIL-005",c);}
static Status prep_write(CourtContext*c,const char*id,FileRoot*r,ObjectStore*s,FileWritePrepared*p,Digest256*old,ObjectRef*neo){std::wstring wid;for(auto*q=id;*q;q++)wid.push_back((wchar_t)*q);auto st=make_root(c,wid.c_str(),r,s);if(st!=Status::Ok)return st;auto target=(std::filesystem::path(r->configured_path)/L"target.bin").wstring();file_write_durable(target,{(const u8*)"OLD",3},false);sha256({(const u8*)"OLD",3},old);object_put(s,{(const u8*)"NEW",3},1,neo);return file_write_prepare(r,s,L"target.bin",*neo,true,old,true,p);}
static CourtResult write_case(const char*id,CourtContext*c){FileRoot r{};ObjectStore s{};FileWritePrepared p{};Digest256 old{};ObjectRef neo{};auto st=prep_write(c,id,&r,&s,&p,&old,&neo);if(st!=Status::Ok)return court_fail(id,CourtDomain::WRITE,st);if(!strcmp(id,"WRT-001")){auto absent=(std::filesystem::path(r.configured_path)/L"target.bin").wstring();DeleteFileW(absent.c_str());st=file_write_prepare(&r,&s,L"target.bin",neo,false,nullptr,false,&p);FileHashResult h{};if(st==Status::Ok)st=file_write_execute(&s,&p,&h);return st==Status::Ok&&h.digest==neo.digest?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,st);}if(!strcmp(id,"WRT-002")){FileHashResult h{};st=file_write_execute(&s,&p,&h);return st==Status::Ok&&h.digest==neo.digest?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,st);}if(!strcmp(id,"WRT-003")){Digest256 wrong{};sha256({(const u8*)"WRONG",5},&wrong);FileWritePrepared x{};st=file_write_prepare(&r,&s,L"target.bin",neo,true,&wrong,true,&x);FileHashResult h{};file_hash_authorized(&r,L"target.bin",&h);return st==Status::FilePreconditionFailed&&h.digest==old?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,Status::TestFailed);}if(!strcmp(id,"WRT-004")){Buffer nb;object_get(&s,&neo,&nb);auto tmp=(std::filesystem::path(r.configured_path)/L"pending.tmp").wstring();file_write_durable(tmp,{nb.data(),(u64)nb.size()},false);FileHashResult h{};file_hash_authorized(&r,L"target.bin",&h);return h.digest==old?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,Status::TestFailed);}if(!strcmp(id,"WRT-005")){FileHashResult h{};st=file_write_execute(&s,&p,&h);FileObservedState o{};FileHashResult rh{};file_write_observe(&p,&o,&rh);return st==Status::Ok&&o==FileObservedState::NEW_STATE?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,st);}if(!strcmp(id,"WRT-006")){FileHashResult h{};st=file_write_execute(&s,&p,&h);if(st==Status::Ok)st=file_write_rollback(&s,&p);FileHashResult back{};file_hash_authorized(&r,L"target.bin",&back);return st==Status::Ok&&back.digest==old?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,st);}if(!strcmp(id,"WRT-007")){FileHashResult h{};file_write_execute(&s,&p,&h);auto target=(std::filesystem::path(r.configured_path)/L"target.bin").wstring();file_write_durable(target,{(const u8*)"THIRD",5},false);st=file_write_rollback(&s,&p);FileHashResult after{};file_hash_authorized(&r,L"target.bin",&after);Digest256 third{};sha256({(const u8*)"THIRD",5},&third);return st==Status::FilePreconditionFailed&&after.digest==third?court_pass(id,CourtDomain::WRITE):court_fail(id,CourtDomain::WRITE,Status::TestFailed);}return court_fail(id,CourtDomain::WRITE,Status::Unsupported);}
CourtResult court_wrt_001(CourtContext*c){return write_case("WRT-001",c);}CourtResult court_wrt_002(CourtContext*c){return write_case("WRT-002",c);}CourtResult court_wrt_003(CourtContext*c){return write_case("WRT-003",c);}CourtResult court_wrt_004(CourtContext*c){return write_case("WRT-004",c);}CourtResult court_wrt_005(CourtContext*c){return write_case("WRT-005",c);}CourtResult court_wrt_006(CourtContext*c){return write_case("WRT-006",c);}CourtResult court_wrt_007(CourtContext*c){return write_case("WRT-007",c);}
}
