from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Iterable, Mapping


@dataclass(frozen=True)
class PlanStep:
    step_id: str
    action: str
    dependencies: tuple[str, ...] = ()
    preconditions: tuple[str, ...] = ()
    effects: tuple[str, ...] = ()
    cost: float = 0.0
    risk: float = 0.0
    authority: str = "AUTOMATIC"

    def validate(self) -> None:
        if not self.step_id or not self.action:
            raise ValueError("step_id and action are required")
        if self.cost < 0 or not 0 <= self.risk <= 1:
            raise ValueError("invalid cost or risk")


@dataclass(frozen=True)
class PlanConstraints:
    initial_facts: tuple[str, ...]
    required_outcomes: tuple[str, ...]
    forbidden_effects: tuple[str, ...] = ()
    allowed_authorities: tuple[str, ...] = ("AUTOMATIC",)
    max_cost: float = float("inf")
    max_risk: float = 1.0


class SymbolicPlanVerifier:
    """Verifies candidate plans generated by humans, rules or neural models."""

    def verify(self, steps: Iterable[PlanStep], constraints: PlanConstraints) -> dict[str, Any]:
        ordered = list(steps)
        ids = [step.step_id for step in ordered]
        if len(ids) != len(set(ids)):
            return {"valid": False, "reason": "duplicate_step_id", "counterexamples": ids}

        facts = set(constraints.initial_facts)
        completed: set[str] = set()
        total_cost = 0.0
        trace: list[dict[str, Any]] = []
        failures: list[dict[str, Any]] = []

        for index, step in enumerate(ordered):
            step.validate()
            missing_dependencies = sorted(set(step.dependencies) - completed)
            missing_preconditions = sorted(set(step.preconditions) - facts)
            forbidden = sorted(set(step.effects) & set(constraints.forbidden_effects))
            authority_invalid = step.authority not in constraints.allowed_authorities
            risk_invalid = step.risk > constraints.max_risk
            total_cost += step.cost
            cost_invalid = total_cost > constraints.max_cost
            failure = {
                "step_id": step.step_id,
                "index": index,
                "missing_dependencies": missing_dependencies,
                "missing_preconditions": missing_preconditions,
                "forbidden_effects": forbidden,
                "authority_invalid": authority_invalid,
                "risk_invalid": risk_invalid,
                "cost_invalid": cost_invalid,
            }
            if any(
                [
                    missing_dependencies,
                    missing_preconditions,
                    forbidden,
                    authority_invalid,
                    risk_invalid,
                    cost_invalid,
                ]
            ):
                failures.append(failure)
                break
            facts.update(step.effects)
            completed.add(step.step_id)
            trace.append({"step": asdict(step), "facts_after": sorted(facts), "total_cost": total_cost})

        missing_outcomes = sorted(set(constraints.required_outcomes) - facts)
        if missing_outcomes:
            failures.append({"step_id": None, "missing_outcomes": missing_outcomes})

        return {
            "valid": not failures,
            "counterexamples": failures,
            "trace": trace,
            "final_facts": sorted(facts),
            "total_cost": total_cost,
            "completed_steps": sorted(completed),
        }


class NeuroSymbolicPlanner:
    """Selects the best constraint-valid candidate from external generators."""

    def select(
        self,
        candidates: Mapping[str, Iterable[PlanStep]],
        constraints: PlanConstraints,
        utility: Mapping[str, float] | None = None,
    ) -> dict[str, Any]:
        weights = dict(utility or {"cost": 0.6, "risk": 0.4})
        evaluated: list[dict[str, Any]] = []
        verifier = SymbolicPlanVerifier()
        for candidate_id, steps_iter in candidates.items():
            steps = list(steps_iter)
            proof = verifier.verify(steps, constraints)
            risk = sum(step.risk for step in steps)
            score = -(proof["total_cost"] * weights.get("cost", 0.0) + risk * weights.get("risk", 0.0))
            evaluated.append(
                {
                    "candidate_id": candidate_id,
                    "valid": proof["valid"],
                    "score": score,
                    "proof": proof,
                    "steps": [asdict(step) for step in steps],
                }
            )
        valid = [item for item in evaluated if item["valid"]]
        if not valid:
            return {"selected": None, "evaluated": evaluated, "valid": False}
        selected = max(valid, key=lambda item: (item["score"], item["candidate_id"]))
        return {"selected": selected, "evaluated": evaluated, "valid": True}
