#include "fuse/base.h"
#include "fuse/status.h"
#include <cstring>

namespace fuse {
void bytes_zero(u8*p,u64 n){if(p&&n)std::memset(p,0,(size_t)n);}void bytes_copy(u8*d,const u8*s,u64 n){if(n)std::memcpy(d,s,(size_t)n);}bool bytes_equal(const u8*a,const u8*b,u64 n){return n==0||std::memcmp(a,b,(size_t)n)==0;}
void put_u16_le(u8*p,u16 v){p[0]=(u8)v;p[1]=(u8)(v>>8);}void put_u32_le(u8*p,u32 v){for(int i=0;i<4;i++)p[i]=(u8)(v>>(i*8));}void put_u64_le(u8*p,u64 v){for(int i=0;i<8;i++)p[i]=(u8)(v>>(i*8));}u16 get_u16_le(const u8*p){return (u16)p[0]|((u16)p[1]<<8);}u32 get_u32_le(const u8*p){u32 v=0;for(int i=0;i<4;i++)v|=(u32)p[i]<<(i*8);return v;}u64 get_u64_le(const u8*p){u64 v=0;for(int i=0;i<8;i++)v|=(u64)p[i]<<(i*8);return v;}
std::string hex(ByteSpan s){static const char h[]="0123456789abcdef";std::string o;o.resize((size_t)s.size*2);for(u64 i=0;i<s.size;i++){o[(size_t)i*2]=h[s.data[i]>>4];o[(size_t)i*2+1]=h[s.data[i]&15];}return o;}
bool unhex(const std::string&s,MutableByteSpan out){if(s.size()!=out.size*2)return false;auto v=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;};for(u64 i=0;i<out.size;i++){int a=v(s[(size_t)i*2]),b=v(s[(size_t)i*2+1]);if(a<0||b<0)return false;out.data[i]=(u8)((a<<4)|b);}return true;}
std::string digest_hex(const Digest256&d){return hex({d.bytes.data(),32});}
Id128 id_from_seed(const char*s){Id128 id{};u64 a=1469598103934665603ull,b=1099511628211ull;for(const unsigned char*p=(const unsigned char*)s;*p;p++){a^=*p;a*=1099511628211ull;b^=(a+*p);b*=1469598103934665603ull;}put_u64_le(id.bytes.data(),a);put_u64_le(id.bytes.data()+8,b);return id;}
const char* status_name(Status s){switch(s){case Status::Ok:return "OK";case Status::InvalidArgument:return "INVALID_ARGUMENT";case Status::BufferTooSmall:return "BUFFER_TOO_SMALL";case Status::IntegerOverflow:return "INTEGER_OVERFLOW";case Status::MemoryFailed:return "MEMORY_FAILED";case Status::CryptoError:return "CRYPTO_ERROR";case Status::BadMagic:return "BAD_MAGIC";case Status::BadVersion:return "BAD_VERSION";case Status::BadLength:return "BAD_LENGTH";case Status::BadDigest:return "BAD_DIGEST";case Status::FieldOrder:return "FIELD_ORDER";case Status::ReservedNonZero:return "RESERVED_NONZERO";case Status::UnknownCritical:return "UNKNOWN_CRITICAL";case Status::TypeLengthMismatch:return "TYPE_LENGTH_MISMATCH";case Status::FileOpenFailed:return "FILE_OPEN_FAILED";case Status::FileReadFailed:return "FILE_READ_FAILED";case Status::FileWriteFailed:return "FILE_WRITE_FAILED";case Status::FileFlushFailed:return "FILE_FLUSH_FAILED";case Status::FileMoveFailed:return "FILE_MOVE_FAILED";case Status::FileNotFound:return "FILE_NOT_FOUND";case Status::FileTypeInvalid:return "FILE_TYPE_INVALID";case Status::FileIdentityFailed:return "FILE_IDENTITY_FAILED";case Status::FileChangedDuringRead:return "FILE_CHANGED_DURING_READ";case Status::FilePreconditionFailed:return "FILE_PRECONDITION_FAILED";case Status::PathInvalid:return "PATH_INVALID";case Status::PathEscape:return "PATH_ESCAPE";case Status::ReparseEscape:return "REPARSE_ESCAPE";case Status::JournalCorrupt:return "JOURNAL_CORRUPT";case Status::JournalTornTail:return "JOURNAL_TORN_TAIL";case Status::JournalCorruptNonFinal:return "JOURNAL_CORRUPT_NONFINAL";case Status::JournalSegmentGap:return "JOURNAL_SEGMENT_GAP";case Status::JournalSequenceInvalid:return "JOURNAL_SEQUENCE_INVALID";case Status::JournalPredecessorInvalid:return "JOURNAL_PREDECESSOR_INVALID";case Status::ObjectCorrupt:return "OBJECT_CORRUPT";case Status::IdentityError:return "IDENTITY_ERROR";case Status::NonceReplay:return "NONCE_REPLAY";case Status::IdempotencyReplay:return "IDEMPOTENCY_REPLAY";case Status::PermitAlreadyConsumed:return "PERMIT_ALREADY_CONSUMED";case Status::Unsupported:return "UNSUPPORTED";default:return "TEST_FAILED";}}
}
