#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/capability.h"
#include <filesystem>
namespace fuse {
Status resolve_authorized_target(const FileRoot*,const std::wstring&,std::wstring*);Status file_write_durable(const std::wstring&,ByteSpan,bool);Status file_hash_handle(HANDLE,FileHashResult*);
static Status digest_path_if_exists(const FileRoot*r,const std::wstring&rel,bool*present,Digest256*out){FileHashResult h{};auto st=file_hash_authorized(r,rel,&h);if(st==Status::FileNotFound){*present=false;return Status::Ok;}if(st!=Status::Ok)return st;*present=true;*out=h.digest;return Status::Ok;}
Status file_write_prepare(const FileRoot*r,const ObjectStore*s,const std::wstring&rel,const ObjectRef&neo,bool expect_present,const Digest256*expect,bool rollback,FileWritePrepared*out){if(!r||!s||!out||!r->write_allowed)return Status::InvalidArgument;auto st=object_verify(s,&neo);if(st!=Status::Ok)return st;std::wstring target;if((st=resolve_authorized_target(r,rel,&target))!=Status::Ok)return st;bool present=false;Digest256 current{};st=digest_path_if_exists(r,rel,&present,&current);if(st!=Status::Ok)return st;if(present!=expect_present)return Status::FilePreconditionFailed;if(present&&(!expect||current!=*expect))return Status::FilePreconditionFailed;*out=FileWritePrepared{};out->root=*r;out->relative_path=rel;out->new_object=neo;out->old_present=present;out->old_digest=current;out->rollback_required=rollback;if(rollback&&present){Buffer old;FileIdentity id{};st=file_read_authorized(r,rel,&old,&id);if(st!=Status::Ok)return st;if((st=object_put(s,{old.data(),(u64)old.size()},0x2001,&out->rollback_object))!=Status::Ok)return st;}FcbWriter w{};fcb_begin(&w,0x2002,0);auto u8rel=(const u8*)rel.data();fcb_put_bytes(&w,1,FcbType::BYTES,{u8rel,(u64)(rel.size()*sizeof(wchar_t))});fcb_put_bytes(&w,2,FcbType::DIGEST256,{neo.digest.bytes.data(),32});Buffer b;return fcb_finish(&w,&b,&out->prepared_digest);}
Status file_write_execute(const ObjectStore*s,const FileWritePrepared*a,FileHashResult*out){if(!s||!a||!out)return Status::InvalidArgument;Buffer neo;auto st=object_get(s,&a->new_object,&neo);if(st!=Status::Ok)return st;std::wstring target;if((st=resolve_authorized_target(&a->root,a->relative_path,&target))!=Status::Ok)return st;u8 rnd[8]{};if((st=random_bytes({rnd,8}))!=Status::Ok)return st;auto hs=hex({rnd,8});std::wstring whs(hs.begin(),hs.end());auto tmp=target+L".fuse-"+whs+L".tmp";if((st=file_write_durable(tmp,{neo.data(),(u64)neo.size()},true))!=Status::Ok)return st;HANDLE th=CreateFileW(tmp.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(th==INVALID_HANDLE_VALUE){DeleteFileW(tmp.c_str());return Status::FileOpenFailed;}FileHashResult check{};st=file_hash_handle(th,&check);CloseHandle(th);if(st!=Status::Ok||check.digest!=a->new_object.digest){DeleteFileW(tmp.c_str());return Status::BadDigest;}if(!MoveFileExW(tmp.c_str(),target.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){DeleteFileW(tmp.c_str());return Status::FileMoveFailed;}return file_hash_authorized(&a->root,a->relative_path,out);}
Status file_write_observe(const FileWritePrepared*a,FileObservedState*state,FileHashResult*out){if(!a||!state||!out)return Status::InvalidArgument;auto st=file_hash_authorized(&a->root,a->relative_path,out);if(st==Status::FileNotFound){*state=FileObservedState::ABSENT;return Status::Ok;}if(st!=Status::Ok)return st;if(out->digest==a->new_object.digest)*state=FileObservedState::NEW_STATE;else if(a->old_present&&out->digest==a->old_digest)*state=FileObservedState::OLD_STATE;else *state=FileObservedState::THIRD_STATE;return Status::Ok;}
Status file_write_rollback(const ObjectStore*s,const FileWritePrepared*a){if(!s||!a||!a->rollback_required||!a->old_present)return Status::Unsupported;FileHashResult cur{};auto st=file_hash_authorized(&a->root,a->relative_path,&cur);if(st!=Status::Ok)return st;if(cur.digest!=a->new_object.digest)return Status::FilePreconditionFailed;Buffer old;if((st=object_get(s,&a->rollback_object,&old))!=Status::Ok)return st;std::wstring target;if((st=resolve_authorized_target(&a->root,a->relative_path,&target))!=Status::Ok)return st;return file_write_durable(target,{old.data(),(u64)old.size()},false);}
}
