#include "fuse/format.h"
namespace fuse {
Status fcb_begin(FcbWriter*w,u16 type,u32 flags){if(!w)return Status::InvalidArgument;*w=FcbWriter{};w->bytes.resize(FCB1_HEADER_SIZE,0);auto*p=w->bytes.data();p[0]='F';p[1]='C';p[2]='B';p[3]='1';put_u16_le(p+4,1);put_u16_le(p+6,type);put_u32_le(p+8,flags);return Status::Ok;}
Status fcb_put_bytes(FcbWriter*w,u32 id,FcbType t,ByteSpan v,u8 flags){if(!w||w->sealed||id==0||(!v.data&&v.size))return Status::InvalidArgument;if(id<=w->last_field_id)return Status::FieldOrder;size_t p=w->bytes.size();w->bytes.resize(p+FCB1_FIELD_HEADER_SIZE+(size_t)v.size);put_u32_le(w->bytes.data()+p,id);w->bytes[p+4]=(u8)t;w->bytes[p+5]=flags;put_u16_le(w->bytes.data()+p+6,0);put_u64_le(w->bytes.data()+p+8,v.size);if(v.size)bytes_copy(w->bytes.data()+p+16,v.data,v.size);w->field_count++;w->last_field_id=id;return Status::Ok;}
Status fcb_put_u64(FcbWriter*w,u32 id,u64 v,u8 flags){u8 b[8];put_u64_le(b,v);return fcb_put_bytes(w,id,FcbType::U64,{b,8},flags);}
Status fcb_finish(FcbWriter*w,Buffer*out,Digest256*d){if(!w||w->sealed||!out)return Status::InvalidArgument;put_u32_le(w->bytes.data()+12,w->field_count);put_u64_le(w->bytes.data()+16,(u64)w->bytes.size()-FCB1_HEADER_SIZE);Digest256 h{};auto st=sha256({w->bytes.data(),(u64)w->bytes.size()},&h);if(st!=Status::Ok)return st;w->bytes.insert(w->bytes.end(),h.bytes.begin(),h.bytes.end());w->sealed=true;*out=w->bytes;if(d)*d=h;return Status::Ok;}
Status fcb_validate(ByteSpan r){if(!r.data||r.size<FCB1_HEADER_SIZE+32)return Status::BadLength;auto*p=r.data;if(p[0]!='F'||p[1]!='C'||p[2]!='B'||p[3]!='1')return Status::BadMagic;if(get_u16_le(p+4)!=1)return Status::BadVersion;u32 exp=get_u32_le(p+12);u64 payload=get_u64_le(p+16);if(payload>r.size||FCB1_HEADER_SIZE+payload+32!=r.size)return Status::BadLength;u64 pos=FCB1_HEADER_SIZE,end=FCB1_HEADER_SIZE+payload;u32 prev=0,count=0;while(pos<end){if(end-pos<16)return Status::BadLength;u32 id=get_u32_le(p+pos);u8 type=p[pos+4],flags=p[pos+5];u16 reserved=get_u16_le(p+pos+6);u64 len=get_u64_le(p+pos+8);if(id==0||id<=prev)return Status::FieldOrder;if(reserved)return Status::ReservedNonZero;if(len>end-pos-16)return Status::BadLength;if(type==(u8)FcbType::U64&&len!=8)return Status::TypeLengthMismatch;if(type==(u8)FcbType::DIGEST256&&len!=32)return Status::TypeLengthMismatch;if(type<1||type>4){if(flags&FCB_FIELD_CRITICAL)return Status::UnknownCritical;}prev=id;count++;pos+=16+len;}if(pos!=end||count!=exp)return Status::BadLength;Digest256 h{};auto st=sha256({p,r.size-32},&h);if(st!=Status::Ok)return st;return bytes_equal(h.bytes.data(),p+r.size-32,32)?Status::Ok:Status::BadDigest;}
Status fcb_first(ByteSpan r,FcbFieldView*out){if(!out)return Status::InvalidArgument;auto st=fcb_validate(r);if(st!=Status::Ok)return st;u64 payload=get_u64_le(r.data+16);if(!payload)return Status::FileNotFound;u64 pos=24;out->id=get_u32_le(r.data+pos);out->type=(FcbType)r.data[pos+4];out->flags=r.data[pos+5];u64 len=get_u64_le(r.data+pos+8);out->value={r.data+pos+16,len};out->next_offset=pos+16+len;return Status::Ok;}
Status fcb_next(ByteSpan r,const FcbFieldView&cur,FcbFieldView*out){if(!out)return Status::InvalidArgument;u64 end=24+get_u64_le(r.data+16),pos=cur.next_offset;if(pos>=end)return Status::FileNotFound;out->id=get_u32_le(r.data+pos);out->type=(FcbType)r.data[pos+4];out->flags=r.data[pos+5];u64 len=get_u64_le(r.data+pos+8);out->value={r.data+pos+16,len};out->next_offset=pos+16+len;return Status::Ok;}
Status fcb_get_bytes(ByteSpan r,u32 wanted,ByteSpan*out){if(!out)return Status::InvalidArgument;FcbFieldView f{};auto st=fcb_first(r,&f);while(st==Status::Ok){if(f.id==wanted){*out=f.value;return Status::Ok;}st=fcb_next(r,f,&f);}return Status::FileNotFound;}Status fcb_get_u64(ByteSpan r,u32 id,u64*out){if(!out)return Status::InvalidArgument;ByteSpan b{};auto st=fcb_get_bytes(r,id,&b);if(st!=Status::Ok)return st;if(b.size!=8)return Status::TypeLengthMismatch;*out=get_u64_le(b.data);return Status::Ok;}
}
