#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/store.h"
#include <filesystem>
#include <algorithm>
namespace fuse {
Status ensure_directory(const std::wstring&);
static std::wstring seg_path(const std::wstring&r,u64 id){wchar_t n[64];swprintf_s(n,L"segment-%016llx.fsj",(unsigned long long)id);return (std::filesystem::path(r)/n).wstring();}
static std::vector<u64> segments(const std::wstring&r){std::vector<u64> ids;WIN32_FIND_DATAW fd{};auto pat=(std::filesystem::path(r)/L"segment-*.fsj").wstring();HANDLE f=FindFirstFileW(pat.c_str(),&fd);if(f==INVALID_HANDLE_VALUE)return ids;do{unsigned long long x=0;if(swscanf_s(fd.cFileName,L"segment-%llx.fsj",&x)==1&&x)ids.push_back((u64)x);}while(FindNextFileW(f,&fd));FindClose(f);std::sort(ids.begin(),ids.end());return ids;}
static Status read_record(HANDLE h,u64 off,u64 size,Buffer*out,u64*next,bool*partial){*partial=false;if(size-off<140){*partial=true;return Status::JournalTornTail;}u8 hdr[140]{};LARGE_INTEGER p{};p.QuadPart=off;if(!SetFilePointerEx(h,p,nullptr,FILE_BEGIN))return Status::FileReadFailed;DWORD got=0;if(!ReadFile(h,hdr,140,&got,nullptr)||got!=140)return Status::FileReadFailed;u64 payload=get_u64_le(hdr+100);if(payload>GENESIS_MAX_RECORD)return Status::JournalCorrupt;u64 total=140+payload+32;if(total>size-off){*partial=true;return Status::JournalTornTail;}out->resize((size_t)total);p.QuadPart=off;SetFilePointerEx(h,p,nullptr,FILE_BEGIN);u64 done=0;while(done<total){DWORD n=0,w=(DWORD)std::min<u64>(0x40000000ull,total-done);if(!ReadFile(h,out->data()+done,w,&n,nullptr)||!n)return Status::FileReadFailed;done+=n;}auto st=fsj_validate({out->data(),(u64)out->size()});if(st!=Status::Ok)return Status::JournalCorrupt;*next=off+total;return Status::Ok;}
Status journal_scan_root(const std::wstring&root,JournalScan*out){if(!out)return Status::InvalidArgument;*out=JournalScan{};ensure_directory(root);auto ids=segments(root);if(ids.empty())return Status::Ok;out->journal_exists=true;out->highest_segment_id=ids.back();Digest256 prev{};u64 expected=1;for(size_t i=0;i<ids.size();i++){if(ids[i]!=(u64)i+1)return Status::JournalSegmentGap;auto p=seg_path(root,ids[i]);HANDLE h=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;LARGE_INTEGER sz{};GetFileSizeEx(h,&sz);u64 off=0;while(off<(u64)sz.QuadPart){Buffer rec;u64 next=0;bool partial=false;auto st=read_record(h,off,(u64)sz.QuadPart,&rec,&next,&partial);if(st!=Status::Ok){CloseHandle(h);if(i+1<ids.size())return Status::JournalCorruptNonFinal;out->tail_damage=true;out->damaged_segment_id=ids[i];out->damage_offset=off;out->damage_reason=st;out->append_segment_id=ids[i];out->append_offset=off;return Status::Ok;}JournalRecordView v{};fsj_view({rec.data(),(u64)rec.size()},&v);if(v.sequence!=expected){CloseHandle(h);return Status::JournalSequenceInvalid;}if(v.previous_record_hash!=prev){CloseHandle(h);return Status::JournalPredecessorInvalid;}prev=v.record_hash;expected++;out->last_sequence=v.sequence;out->last_record_hash=v.record_hash;out->last_record_segment_id=ids[i];out->last_record_end_offset=next;off=next;}CloseHandle(h);out->append_segment_id=ids[i];out->append_offset=off;}return Status::Ok;}
Status journal_writer_open(const std::wstring&root,JournalWriter*w,u64 limit){if(!w)return Status::InvalidArgument;JournalScan s{};auto st=journal_recover(root,&s);if(st!=Status::Ok)return st;w->root=root;w->segment_id=s.append_segment_id?s.append_segment_id:1;w->segment_size=s.append_offset;w->next_sequence=s.last_sequence+1;w->previous_hash=s.last_record_hash;w->segment_limit=limit;return Status::Ok;}
Status journal_append(JournalWriter*w,const Id128*mid,u64 mv,u32 et,ByteSpan payload,Digest256*out_hash){if(!w||!mid)return Status::InvalidArgument;JournalRecordInput in{};in.sequence=w->next_sequence;in.mission_id=*mid;in.mission_version=mv;in.event_type=et;in.previous_record_hash=w->previous_hash;in.payload=payload;Buffer rec;Digest256 rh{};auto st=fsj_build(&in,&rec,&rh);if(st!=Status::Ok)return st;if(w->segment_size&&w->segment_size+rec.size()>w->segment_limit){w->segment_id++;w->segment_size=0;}auto p=seg_path(w->root,w->segment_id);ensure_directory(w->root);HANDLE h=CreateFileW(p.c_str(),GENERIC_READ|GENERIC_WRITE,FILE_SHARE_READ,nullptr,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL|FILE_FLAG_WRITE_THROUGH,nullptr);if(h==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;LARGE_INTEGER pos{};pos.QuadPart=w->segment_size;SetFilePointerEx(h,pos,nullptr,FILE_BEGIN);u64 off=0;while(off<rec.size()){DWORD n=0,want=(DWORD)std::min<u64>(0x40000000ull,rec.size()-off);if(!WriteFile(h,rec.data()+off,want,&n,nullptr)||!n){CloseHandle(h);return Status::FileWriteFailed;}off+=n;}if(!FlushFileBuffers(h)){CloseHandle(h);return Status::FileFlushFailed;}Buffer rb(rec.size());pos.QuadPart=w->segment_size;SetFilePointerEx(h,pos,nullptr,FILE_BEGIN);DWORD got=0;if(!ReadFile(h,rb.data(),(DWORD)rb.size(),&got,nullptr)||got!=rb.size()){CloseHandle(h);return Status::FileReadFailed;}CloseHandle(h);if(rb!=rec)return Status::BadDigest;w->segment_size+=rec.size();w->next_sequence++;w->previous_hash=rh;if(out_hash)*out_hash=rh;return Status::Ok;}
Status journal_replay_all(const std::wstring&root,ReplayFn fn,void*ctx){auto ids=segments(root);Digest256 prev{};u64 expected=1;for(auto id:ids){auto p=seg_path(root,id);HANDLE h=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;LARGE_INTEGER sz{};GetFileSizeEx(h,&sz);u64 off=0;while(off<(u64)sz.QuadPart){Buffer rec;u64 next=0;bool partial=false;auto st=read_record(h,off,(u64)sz.QuadPart,&rec,&next,&partial);if(st!=Status::Ok){CloseHandle(h);return st;}JournalRecordView v{};fsj_view({rec.data(),(u64)rec.size()},&v);if(v.sequence!=expected||v.previous_record_hash!=prev){CloseHandle(h);return Status::JournalPredecessorInvalid;}if(fn&&(st=fn(&v,ctx))!=Status::Ok){CloseHandle(h);return st;}prev=v.record_hash;expected++;off=next;}CloseHandle(h);}return Status::Ok;}
}
