#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/store.h"
#include <filesystem>
namespace fuse {
Status ensure_directory(const std::wstring&);Status file_read_path(const std::wstring&,Buffer*);Status file_write_durable(const std::wstring&,ByteSpan,bool);bool path_exists(const std::wstring&);
Status object_store_open(const std::wstring&r,ObjectStore*out){if(!out)return Status::InvalidArgument;out->root=r;return ensure_directory(r);}std::wstring object_path(const ObjectStore*s,const Digest256&d){auto h=digest_hex(d);auto p=std::filesystem::path(s->root)/std::wstring(h.begin(),h.begin()+2)/std::wstring(h.begin()+2,h.begin()+4);ensure_directory(p.wstring());return (p/std::wstring(h.begin(),h.end())).replace_extension(L".fso").wstring();}
Status object_verify_path(const std::wstring&p,const ObjectRef*r){Buffer b;auto st=file_read_path(p,&b);if(st!=Status::Ok)return st;if(b.size()<48||b[0]!='F'||b[1]!='S'||b[2]!='O'||b[3]!='1'||get_u16_le(b.data()+4)!=1)return Status::ObjectCorrupt;u64 n=get_u64_le(b.data()+8);if(48+n!=b.size()||n!=r->size||!bytes_equal(b.data()+16,r->digest.bytes.data(),32))return Status::ObjectCorrupt;Digest256 h{};st=sha256({b.data()+48,n},&h);return st==Status::Ok&&h==r->digest?Status::Ok:Status::ObjectCorrupt;}
Status object_verify(const ObjectStore*s,const ObjectRef*r){return object_verify_path(object_path(s,r->digest),r);}Status object_put(const ObjectStore*s,ByteSpan payload,u16 ct,ObjectRef*out){if(!s||!out)return Status::InvalidArgument;Digest256 d{};auto st=sha256(payload,&d);if(st!=Status::Ok)return st;ObjectRef r{d,payload.size,ct,0};auto p=object_path(s,d);if(path_exists(p)){st=object_verify_path(p,&r);if(st==Status::Ok)*out=r;return st;}Buffer b(48+(size_t)payload.size,0);b[0]='F';b[1]='S';b[2]='O';b[3]='1';put_u16_le(b.data()+4,1);put_u16_le(b.data()+6,0);put_u64_le(b.data()+8,payload.size);bytes_copy(b.data()+16,d.bytes.data(),32);if(payload.size)bytes_copy(b.data()+48,payload.data,payload.size);auto tmp=p+L".tmp";st=file_write_durable(tmp,{b.data(),(u64)b.size()},true);if(st!=Status::Ok)return st;if((st=object_verify_path(tmp,&r))!=Status::Ok){DeleteFileW(tmp.c_str());return st;}if(!MoveFileExW(tmp.c_str(),p.c_str(),MOVEFILE_WRITE_THROUGH)){auto e=GetLastError();DeleteFileW(tmp.c_str());if(e==ERROR_ALREADY_EXISTS||e==ERROR_FILE_EXISTS)st=object_verify_path(p,&r);else st=Status::FileMoveFailed;}if(st==Status::Ok)*out=r;return st;}
Status object_get(const ObjectStore*s,const ObjectRef*r,Buffer*out){auto st=object_verify(s,r);if(st!=Status::Ok)return st;Buffer b;st=file_read_path(object_path(s,r->digest),&b);if(st!=Status::Ok)return st;out->assign(b.begin()+48,b.end());return Status::Ok;}
}
