#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/store.h"
#include <filesystem>
namespace fuse {
Status ensure_directory(const std::wstring&);Status file_read_path(const std::wstring&,Buffer*);Status file_write_durable(const std::wstring&,ByteSpan,bool);
static std::wstring seg_path2(const std::wstring&r,u64 id){wchar_t n[64];swprintf_s(n,L"segment-%016llx.fsj",(unsigned long long)id);return (std::filesystem::path(r)/n).wstring();}
Status journal_recover(const std::wstring&root,JournalScan*out){JournalScan s{};auto st=journal_scan_root(root,&s);if(st!=Status::Ok)return st;if(!s.tail_damage){*out=s;return Status::Ok;}auto p=seg_path2(root,s.damaged_segment_id);HANDLE h=CreateFileW(p.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL|FILE_FLAG_WRITE_THROUGH,nullptr);if(h==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;LARGE_INTEGER sz{};GetFileSizeEx(h,&sz);if((u64)sz.QuadPart<s.damage_offset){CloseHandle(h);return Status::JournalCorrupt;}u64 rem=(u64)sz.QuadPart-s.damage_offset;Buffer bad((size_t)rem);LARGE_INTEGER pos{};pos.QuadPart=s.damage_offset;SetFilePointerEx(h,pos,nullptr,FILE_BEGIN);DWORD got=0;if(rem&&(!ReadFile(h,bad.data(),(DWORD)bad.size(),&got,nullptr)||got!=bad.size())){CloseHandle(h);return Status::FileReadFailed;}auto qdir=(std::filesystem::path(root)/L"quarantine").wstring();ensure_directory(qdir);auto q=(std::filesystem::path(qdir)/L"tail.bad").wstring();if(rem){st=file_write_durable(q,{bad.data(),(u64)bad.size()},false);if(st!=Status::Ok){CloseHandle(h);return st;}}pos.QuadPart=s.damage_offset;SetFilePointerEx(h,pos,nullptr,FILE_BEGIN);if(!SetEndOfFile(h)||!FlushFileBuffers(h)){CloseHandle(h);return Status::FileFlushFailed;}CloseHandle(h);st=journal_scan_root(root,out);if(st!=Status::Ok||out->tail_damage)return Status::JournalCorrupt;return Status::Ok;}
static constexpr u64 HEAD_SIZE=168;
static Status encode_head(const HeadState&x,Buffer*out){out->assign(HEAD_SIZE,0);auto*p=out->data();p[0]='F';p[1]='G';p[2]='H';p[3]='1';put_u16_le(p+4,1);put_u16_le(p+6,(u16)HEAD_SIZE);put_u64_le(p+8,x.generation);put_u64_le(p+16,x.segment_id);put_u64_le(p+24,x.journal_offset);put_u64_le(p+32,x.sequence);bytes_copy(p+40,x.journal_hash.bytes.data(),32);bytes_copy(p+72,x.snapshot_hash.bytes.data(),32);bytes_copy(p+104,x.state_root.bytes.data(),32);Digest256 h{};auto st=sha256({p,136},&h);if(st!=Status::Ok)return st;bytes_copy(p+136,h.bytes.data(),32);return Status::Ok;}
static Status decode_head(ByteSpan b,HeadState*out){if(b.size!=HEAD_SIZE||b.data[0]!='F'||b.data[1]!='G'||b.data[2]!='H'||b.data[3]!='1')return Status::BadMagic;Digest256 h{};auto st=sha256({b.data,136},&h);if(st!=Status::Ok||!bytes_equal(h.bytes.data(),b.data+136,32))return Status::BadDigest;out->generation=get_u64_le(b.data+8);out->segment_id=get_u64_le(b.data+16);out->journal_offset=get_u64_le(b.data+24);out->sequence=get_u64_le(b.data+32);bytes_copy(out->journal_hash.bytes.data(),b.data+40,32);return Status::Ok;}
Status head_reconstruct(const std::wstring&root,const JournalScan&s,u64 gen,HeadState*out){HeadState h{};h.generation=gen+1;h.segment_id=s.last_record_segment_id;h.journal_offset=s.last_record_end_offset;h.sequence=s.last_sequence;h.journal_hash=s.last_record_hash;Buffer b;auto st=encode_head(h,&b);if(st!=Status::Ok)return st;auto name=(h.generation&1)?L"HEAD.A":L"HEAD.B";auto p=(std::filesystem::path(root)/name).wstring();st=file_write_durable(p,{b.data(),(u64)b.size()},false);if(st==Status::Ok)*out=h;return st;}
Status head_load_best(const std::wstring&root,HeadState*out){bool ok=false;HeadState best{};for(auto n:{L"HEAD.A",L"HEAD.B"}){Buffer b;auto st=file_read_path((std::filesystem::path(root)/n).wstring(),&b);if(st!=Status::Ok)continue;HeadState h{};if(decode_head({b.data(),(u64)b.size()},&h)==Status::Ok&&(!ok||h.generation>best.generation)){best=h;ok=true;}}if(!ok)return Status::FileNotFound;*out=best;return Status::Ok;}
}
