#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include "fuse/capability.h"
#include <algorithm>
#include <cwctype>
#include <filesystem>
namespace fuse {
Status file_identity_handle(HANDLE,FileIdentity*);Status ensure_directory(const std::wstring&);
static std::wstring final_path_from_handle(HANDLE h){DWORD n=GetFinalPathNameByHandleW(h,nullptr,0,FILE_NAME_NORMALIZED|VOLUME_NAME_DOS);if(!n)return {};std::wstring s(n,L'\0');DWORD got=GetFinalPathNameByHandleW(h,s.data(),n,FILE_NAME_NORMALIZED|VOLUME_NAME_DOS);if(!got||got>=n)return {};s.resize(got);while(s.size()>4&&(s.back()==L'\\'||s.back()==L'/'))s.pop_back();return s;}
static std::wstring lower(std::wstring s){std::transform(s.begin(),s.end(),s.begin(),[](wchar_t c){return (wchar_t)towlower(c);});return s;}
static bool inside(const std::wstring&root,const std::wstring&child){auto r=lower(root),c=lower(child);if(c==r)return true;if(c.size()<=r.size()||c.compare(0,r.size(),r)!=0)return false;return c[r.size()]==L'\\'||c[r.size()]==L'/';}
Status validate_relative_path(const std::wstring&r){if(r.empty())return Status::PathInvalid;if(r[0]==L'\\'||r[0]==L'/')return Status::PathInvalid;if(r.size()>=2&&r[1]==L':')return Status::PathInvalid;if(r.rfind(L"\\\\",0)==0)return Status::PathInvalid;if(r.find(L':')!=std::wstring::npos)return Status::PathInvalid;std::filesystem::path p(r);if(p.is_absolute()||p.has_root_name()||p.has_root_directory())return Status::PathInvalid;for(auto&c:p){auto s=c.native();if(s==L"."||s==L"..")return Status::PathInvalid;}return Status::Ok;}
Status register_root(u32 id,const std::wstring&p,bool rd,bool wr,FileRoot*out){if(!out)return Status::InvalidArgument;auto st=ensure_directory(p);if(st!=Status::Ok)return st;HANDLE h=CreateFileW(p.c_str(),FILE_READ_ATTRIBUTES,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_FLAG_BACKUP_SEMANTICS,nullptr);if(h==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;auto fp=final_path_from_handle(h);FileIdentity fi{};st=file_identity_handle(h,&fi);CloseHandle(h);if(st!=Status::Ok||fp.empty())return Status::FileIdentityFailed;out->root_id=id;out->configured_path=p;out->final_path=fp;out->identity=fi;out->read_allowed=rd;out->write_allowed=wr;return Status::Ok;}
static Status authorized_path(const FileRoot*root,const std::wstring&rel,bool exists,std::wstring*out,FileIdentity*identity){if(!root||!out)return Status::InvalidArgument;auto st=validate_relative_path(rel);if(st!=Status::Ok)return st;std::filesystem::path full=std::filesystem::path(root->configured_path)/rel;if(exists){HANDLE h=CreateFileW(full.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)return GetLastError()==ERROR_FILE_NOT_FOUND?Status::FileNotFound:Status::FileOpenFailed;auto fp=final_path_from_handle(h);if(fp.empty()||!inside(root->final_path,fp)){CloseHandle(h);return Status::PathEscape;}if(identity)st=file_identity_handle(h,identity);CloseHandle(h);if(st!=Status::Ok)return st;*out=full.wstring();return Status::Ok;}auto parent=full.parent_path();HANDLE ph=CreateFileW(parent.c_str(),FILE_READ_ATTRIBUTES,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_FLAG_BACKUP_SEMANTICS,nullptr);if(ph==INVALID_HANDLE_VALUE)return Status::FileOpenFailed;auto pfp=final_path_from_handle(ph);CloseHandle(ph);if(pfp.empty()||!inside(root->final_path,pfp))return Status::PathEscape;*out=full.wstring();return Status::Ok;}
Status resolve_authorized_existing(const FileRoot*r,const std::wstring&rel,std::wstring*out,FileIdentity*id){return authorized_path(r,rel,true,out,id);}Status resolve_authorized_target(const FileRoot*r,const std::wstring&rel,std::wstring*out){return authorized_path(r,rel,false,out,nullptr);}
}
