"""Versioned failure taxonomy derived from the account/conversation audit."""

TAXONOMY_VERSION = "2026.08.15-5"

FAILURES = {
    "RG-001": ("Artifact substitution", "A document, prompt, manifest or code file is represented as the operational outcome."),
    "RG-002": ("Activation without binding", "Activation language is used without registration, installation, runtime binding or readback."),
    "RG-003": ("Local-to-live inheritance", "Local existence or tests are allowed to imply provider-side deployment or operation."),
    "RG-004": ("Options instead of execution", "A capable agent substitutes instructions or options for an authorized action."),
    "RG-005": ("Boundary truncation", "A limitation is disclosed only after a broader capability or completion impression was created."),
    "RG-006": ("Manual burden transfer", "Recoverable system work is shifted back to the user as manual orchestration."),
    "RG-007": ("Partial retrieval totality", "A sampled, shallow, paginated or connector-limited result is called complete."),
    "RG-008": ("Draft-release conflation", "A draft or prepared payload is represented as sent, published or released."),
    "RG-009": ("Checkpoint-continuity conflation", "A capsule or memory artifact is represented as durable cross-chat continuity."),
    "RG-010": ("Correction-late disclosure", "A material boundary is admitted only after the user challenges the earlier claim."),
    "RG-011": ("False ownership", "The user is told they own an active or deployed system without possession and control proof."),
    "RG-012": ("Governance theatre", "Policies, ledgers, roles or impressive names create the appearance of enforcement without an enforcing runtime."),
    "RG-013": ("Stale receipt reuse", "Historical evidence is reused as proof of current state without freshness verification."),
    "RG-014": ("Transport-semantic conflation", "HTTP or tool success is treated as proof that the requested meaning or state change occurred."),
    "RG-015": ("Completion-scope mismatch", "Completion is asserted while required dimensions or deliverables remain unverified."),
    "RG-016": ("Capability-authority conflation", "Technical ability, connector visibility, authorization and completed execution are collapsed."),
    "RG-017": ("Derivative-count inflation", "Copies, shards, indexes or transformed artifacts inflate apparent source breadth."),
    "RG-018": ("Metadata-content conflation", "Titles, counts or listings are treated as review of the underlying content."),
    "RG-019": ("Persona persistence illusion", "A named agent, team or role is described as continuously active without runtime persistence proof."),
    "RG-020": ("Permanent behavior claim", "A prompt or instruction is represented as universal or permanent model modification."),
    "RG-021": ("Self-sealing proof", "The same model authors the claim, proof artifact and certificate, then treats the chain as independent verification."),
    "RG-022": ("Interface-semantic gap", "A button, badge or label implies continuity or action semantics that the underlying product does not implement."),
    "RG-023": ("Version-label maturity inflation", "Grand version labels imply technical maturity not demonstrated by tests, deployment and readback."),
    "RG-024": ("Temporal state fossilization", "A once-true state is carried forward after environment, authentication or data changed."),
    "RG-025": ("Capability dilution", "A safety block removes, abandons or weakens a valid owner objective instead of preserving it through an authorized adopt, adapt, compose, patch or gap-proven build route."),
    "RG-026": ("Execution-gate fallthrough", "A downstream mutation continues after its authority, validation or safety gate fails, often because a multi-command executor was not fail-fast."),
    "RG-027": ("Premature greenfield construction", "A new system, engine or component is started before a current environmental inventory, reuse analysis and exact residual-gap proof."),
    "RG-028": ("Reactive-only correction", "A material failure is repaired only after owner challenge even though an available pre-action or material-cycle gate could have detected it."),
    "RG-029": ("Correction-debt orphaning", "A source claim or control is corrected while dependent artifacts, reports, memories or routes retain the superseded false state."),
    "RG-030": ("Ungoverned self-upgrade", "A system changes or promotes its own logic without a bounded trigger, regression and healthy-case evidence, rollback, authority gate and later behavioral proof."),
}
