"""CASEFORGE-Ω scientific benchmark and evolution layer for EvidenceOps."""

from .blind_runner import (
    AgentContext,
    BlindIsolationError,
    BlindRunReceipt,
    HiddenControlScorer,
    IsolatedBlindRunner,
    ModelBinding,
    ScoringReceipt,
    assert_blind_payload,
)
from .capability_decision import (
    BlockerKind,
    CapabilityDecision,
    CapabilityDecisionRequest,
    CapabilityResolutionGate,
    CapabilityScope,
    CapabilityState,
    GateDecision,
    RouteAttempt,
    TerminalClaim,
)
from .core import (
    BENCHMARK_WEIGHTS,
    FATAL_FAILURES,
    BenchmarkEvaluation,
    CandidatePromotionDecision,
    evaluate_benchmark,
    evaluate_candidate_promotion,
    select_next_case,
    to_evolution_metrics,
)
from .federation_adapter import (
    Capability,
    CapabilityPlan,
    SurfaceState,
    build_innovation_frontier,
    select_minimum_sufficient_capabilities,
)
from .federation_evolution_program import (
    ALL_STAGES,
    AUTHORITY_CEILING as EVOLUTION_AUTHORITY_CEILING,
    AutomationClass,
    EvolutionDecision,
    EvolutionMaturity,
    EvolutionStage,
    FederationEvolutionOrchestrator,
    STAGE_SPECS,
    SYSTEM_PROFILES,
    StageEvidence,
    StageSpec,
    StrategyMode,
    SystemEvolutionProfile,
    SystemEvolutionState,
)
from .federation_validation import (
    AutoFixLaboratory,
    CapabilityForge,
    CapabilityForgeResult,
    CapabilityProbe,
    ContinuityForge,
    ContinuityProbe,
    FederationEvaluationContract,
    MaturityState,
    RecoveryTrace,
    promote_contract,
)
from .federation_validation_evolution import to_evolution_governor_metrics
from .scientia import (
    EpistemicState,
    Hypothesis,
    ScientiaKernel,
    ScientificObservation,
)

__all__ = [
    "ALL_STAGES",
    "BENCHMARK_WEIGHTS",
    "FATAL_FAILURES",
    "AgentContext",
    "AutomationClass",
    "AutoFixLaboratory",
    "BenchmarkEvaluation",
    "BlindIsolationError",
    "BlindRunReceipt",
    "BlockerKind",
    "CandidatePromotionDecision",
    "Capability",
    "CapabilityDecision",
    "CapabilityDecisionRequest",
    "CapabilityForge",
    "CapabilityForgeResult",
    "CapabilityPlan",
    "CapabilityProbe",
    "CapabilityResolutionGate",
    "CapabilityScope",
    "CapabilityState",
    "ContinuityForge",
    "ContinuityProbe",
    "EVOLUTION_AUTHORITY_CEILING",
    "EpistemicState",
    "EvolutionDecision",
    "EvolutionMaturity",
    "EvolutionStage",
    "FederationEvaluationContract",
    "FederationEvolutionOrchestrator",
    "GateDecision",
    "HiddenControlScorer",
    "Hypothesis",
    "IsolatedBlindRunner",
    "MaturityState",
    "ModelBinding",
    "RecoveryTrace",
    "RouteAttempt",
    "STAGE_SPECS",
    "SYSTEM_PROFILES",
    "ScientiaKernel",
    "ScientificObservation",
    "ScoringReceipt",
    "StageEvidence",
    "StageSpec",
    "StrategyMode",
    "SurfaceState",
    "SystemEvolutionProfile",
    "SystemEvolutionState",
    "TerminalClaim",
    "assert_blind_payload",
    "build_innovation_frontier",
    "evaluate_benchmark",
    "evaluate_candidate_promotion",
    "promote_contract",
    "select_minimum_sufficient_capabilities",
    "select_next_case",
    "to_evolution_governor_metrics",
    "to_evolution_metrics",
]
