"""CASEFORGE-Ω scientific benchmark and evolution layer for EvidenceOps."""

from .blind_runner import (
    AgentContext,
    BlindIsolationError,
    BlindRunReceipt,
    HiddenControlScorer,
    IsolatedBlindRunner,
    ModelBinding,
    ScoringReceipt,
    assert_blind_payload,
)
from .core import (
    BENCHMARK_WEIGHTS,
    FATAL_FAILURES,
    BenchmarkEvaluation,
    CandidatePromotionDecision,
    evaluate_benchmark,
    evaluate_candidate_promotion,
    select_next_case,
    to_evolution_metrics,
)
from .federation_adapter import (
    Capability,
    CapabilityPlan,
    SurfaceState,
    build_innovation_frontier,
    select_minimum_sufficient_capabilities,
)
from .federation_validation import (
    AutoFixLaboratory,
    CapabilityForge,
    CapabilityForgeResult,
    CapabilityProbe,
    ContinuityForge,
    ContinuityProbe,
    FederationEvaluationContract,
    MaturityState,
    RecoveryTrace,
    promote_contract,
)
from .federation_validation_evolution import to_evolution_governor_metrics
from .scientia import (
    EpistemicState,
    Hypothesis,
    ScientiaKernel,
    ScientificObservation,
)

__all__ = [
    "BENCHMARK_WEIGHTS",
    "FATAL_FAILURES",
    "AgentContext",
    "AutoFixLaboratory",
    "BenchmarkEvaluation",
    "BlindIsolationError",
    "BlindRunReceipt",
    "CandidatePromotionDecision",
    "Capability",
    "CapabilityForge",
    "CapabilityForgeResult",
    "CapabilityPlan",
    "CapabilityProbe",
    "ContinuityForge",
    "ContinuityProbe",
    "EpistemicState",
    "FederationEvaluationContract",
    "HiddenControlScorer",
    "Hypothesis",
    "IsolatedBlindRunner",
    "MaturityState",
    "ModelBinding",
    "RecoveryTrace",
    "ScientiaKernel",
    "ScientificObservation",
    "ScoringReceipt",
    "SurfaceState",
    "assert_blind_payload",
    "build_innovation_frontier",
    "evaluate_benchmark",
    "evaluate_candidate_promotion",
    "promote_contract",
    "select_minimum_sufficient_capabilities",
    "select_next_case",
    "to_evolution_governor_metrics",
    "to_evolution_metrics",
]
